### ISSUE TITLE
验证安装时的提示

### ISSUE THREAD

**Issue by Jasonvon** [open-mmlab/mmyolo#120]
### 📚 The doc issue

用xshell连服务器安装MMYOLO，验证安装时提示如下，就停滞了

local loads checkpoint from path: yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth
/home/***/.conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:170: UserWarning: `Visualizer` backend is not initialized because save_dir is None.
  warnings.warn('`Visualizer` backend is not initialized '

**Comment by RangeKing** [comment]
Hi @Jasonvon，感谢使用。您可以查看一下mmyolo文件夹下是否正常生成了 result.jpg。如果生成，那么说明您已经安装成功。
我们后续也会优化验证安装时的提示逻辑，目前确实比较容易造成困惑。

**Comment by Jasonvon** [comment]
> Hi @Jasonvon，感谢使用MMYOLO。您可以查看一下mmyolo文件夹下是否正常生成了 result.jpg。如果生成，那么说明您已经安装成功。 我们后续也会优化验证安装时的提示逻辑，目前确实比较容易造成困惑。

Hi @RangeKing 停滞整晚依然没有正常生成result.jpg，请问有其他验证方式吗？

**Comment by Jasonvon** [comment]
> Hi @Jasonvon，感谢使用MMYOLO。您可以查看一下mmyolo文件夹下是否正常生成了 result.jpg。如果生成，那么说明您已经安装成功。 我们后续也会优化验证安装时的提示逻辑，目前确实比较容易造成困惑。

hi @RangeKing 停滞整晚依然没有生成result.jpg，请问有其他验证方式吗？

**Comment by RangeKing** [comment]
> hi @RangeKing 停滞整晚依然没有生成result.jpg，请问有其他验证方式吗？

@Jasonvon 您可以尝试跑跑看 [yolov5_tutorial.md](https://github.com/open-mmlab/mmyolo/blob/dev/docs/zh_cn/user_guides/yolov5_tutorial.md#%E6%95%B0%E6%8D%AE%E9%9B%86%E5%87%86%E5%A4%87) #数据集准备 以及之后的内容。

**Comment by JiayuXu0** [comment]
> 

@Jasonvon 因为你是采用远程ssh到开发机上调试，最终可视化时由于是远程调试无法显示，导致键盘事件也响应不了。暂时你先把show改为False即可。
`visualizer.add_datasample(
        'result',
        img,
        data_sample=result,
        draw_gt=False,
        show=False,
        wait_time=0,
        out_file=args.out_file,
        pred_score_thr=args.score_thr)`

**Comment by hhaAndroid** [comment]
@JiayuXu0 we will improve it. Thank you

**Comment by Jasonvon** [comment]
> 

hi @JiayuXu0 能否给更详细的操作步骤呢，如何将show改为False呀

**Comment by JiayuXu0** [comment]
> > 
> 
> hi @JiayuXu0 能否给更详细的操作步骤呢，如何将show改为False呀
<img width="438" alt="image" src="https://user-images.githubusercontent.com/84259897/194794403-d21ebf74-6407-4ceb-badf-2269301fb9c2.png">

**Comment by tcexeexe** [comment]
> > > 
> > 
> > 
> > hi @JiayuXu0 能否给更详细的操作步骤呢，如何将show改为False呀
> 
> <img alt="image" width="438" src="https://user-images.githubusercontent.com/84259897/194794403-d21ebf74-6407-4ceb-badf-2269301fb9c2.png">

在demo/image_demo.py中第53行
![1665655240588](https://user-images.githubusercontent.com/28287196/195567120-26072118-dc43-40c8-979d-80eeaed8841d.png)

**Comment by PeterH0323** [comment]
Hi @Jasonvon 
V0.1.2 的 image_demo 默认不显示图片，若要显示则加上 `--show`：
https://github.com/open-mmlab/mmyolo/blob/0b48313dc757a26ad3087aa17f0991833bd7cc91/demo/image_demo.py#L30-L31

这边我先将 Issue 关掉了，如果您后续有其他什么疑问的话，欢迎继续提交 Issue ，若还需要讨论关于这个的话，可以将这个 issue 重开。
