### ISSUE TITLE
How to Train RTMDet on a Custom Dataset

### ISSUE THREAD

**Issue by David-19940718** [open-mmlab/mmyolo#143]
### Model/Dataset description

Need a step-by-step toturial, better to support yolo-style *.txt format.

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by hhaAndroid** [comment]
@David-19940718 Please follow [this](https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/user_guides/yolov5_tutorial.md)

**Comment by hhaAndroid** [comment]
@David-19940718 We will add this conversion script.

**Comment by SkalskiP** [comment]
Hi 👋🏻 Looks like the link no longer works.
