### ISSUE TITLE
cspnext imagenet pretrained model in RTMDET

### ISSUE THREAD

**Issue by zugofn** [open-mmlab/mmyolo#175]
### What is the problem this feature will solve?

What time will the cspnext pretrained model be relased in the [page](https://github.com/open-mmlab/mmyolo/tree/main/configs/rtmdet/cspnext_imagenet_pretrain)?
Like backbone in RTMDet-m、RTMDet-x、RTMDet-l?

### What is the feature you are proposing to solve the problem?

backbone pretrained model in RTMDet.

**Comment by hhaAndroid** [comment]
@zugofn Large models do not require pre-trained weights, so there is no development plan for the time being.

**Comment by zugofn** [comment]
> @zugofn Large models do not require pre-trained weights, so there is no development plan for the time being.

Thanks for your reply!
So can I train RTMDet-m/x/l directly from scratch without using imagenet pretrained model?

**Comment by hhaAndroid** [comment]
Yes

**Comment by zugofn** [comment]
> Yes

Thanks a lot！
Have a nice day😀
