### ISSUE TITLE
yolov5 data augumentation missing！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmyolo#180]
### 📚 The doc issue

请问下
1 yolov5或v6 训练的时候，采用了哪些数据增广呢？是否有针对不同的物体或者人 检测框box 尺寸和大小随机调整的数据增广呢？ 具体文档链接是？
2 就是说假如前面输入的人检测出来的box 比人要大的多而且尺寸 宽高比也很异常，那么这种情况的数据增广是怎么处理的呢？ 具体代码体现在哪个地方呢？ 具体代码位置是？

### Suggest a potential alternative/fix

just follow

**Comment by hhaAndroid** [comment]
具体链接见： https://mmyolo.readthedocs.io/zh_CN/latest/algorithm_descriptions/yolov5_description.html
