### ISSUE TITLE
Hi I am just wondering I don't understand reduce layer and build layer purpose in your code what does it really mean? in the diagram I really do not get it topdown layer, out layer (0,1,2).

### ISSUE THREAD

**Issue by noreenanwar** [open-mmlab/mmyolo#211]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

NONE

### Environment

NONE

**Comment by hhaAndroid** [comment]
@noreenanwar Thanks a lot for your feedback. We provide a structure diagram, which corresponds to the code, as follows:

![image](https://user-images.githubusercontent.com/17425982/199150937-34391dbd-3bfc-48fe-b31b-822fec6991e3.png)

please refer to https://mmyolo.readthedocs.io/en/latest/algorithm_descriptions/model_design.html for detail. 


`The core purpose is to unify the building process of all YOLO series network structures`

**Comment by noreenanwar** [comment]
thank you
