### ISSUE TITLE
Make pycocotools an optional dependency

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmyolo#235]
### What is the problem this feature will solve?

I run this code on env having mmengine, mmyolo, mmcv, mmdet installed:

```python
from mmdet.apis import init_detector
from mmyolo.utils import register_all_modules

# register all modules in mmdet into the registries
register_all_modules()

# create model
config_path = 'yolov5_n-v61_syncbn_fast_8xb16-300e_coco.py'
model_path = 'yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739-b804c1ad.pth'

model = init_detector(
    config=config_path,
    checkpoint=model_path,
    device='cuda:0',
)

```

I get this error:

```bash
File .../lib/python3.8/site-packages/mmdet/apis/__init__.py:2, in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .inference import (async_inference_detector, inference_detector,
      3                         init_detector)
      5 __all__ = [
      6     'init_detector',
      7     'async_inference_detector',
      8     'inference_detector',
      9 ]

File .../lib/python3.8/site-packages/mmdet/apis/inference.py:14, in <module>
     11 from mmengine.config import Config
     12 from mmengine.runner import load_checkpoint
---> 14 from ..evaluation import get_classes
     15 from ..models import build_detector
     16 from ..structures import DetDataSample, SampleList

File .../lib/python3.8/site-packages/mmdet/evaluation/__init__.py:3, in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
      2 from .functional import *  # noqa: F401,F403
----> 3 from .metrics import *
...
----> 8 import pycocotools
      9 from pycocotools.coco import COCO as _COCO
     10 from pycocotools.cocoeval import COCOeval as _COCOeval

ModuleNotFoundError: No module named 'pycocotools'
```

Why is `pycocotools` a hard dependency for `mmyolo`? It is not necessary when doing only inference.

### What is the feature you are proposing to solve the problem?

Making `pycocotools` dependency optional when doing inference with mmyolo model.

**Comment by hhaAndroid** [comment]
@fcakyon Strange, `pycocotools` should be automatically installed when mmdet is installed,

https://github.com/open-mmlab/mmdetection/blob/3.x/requirements/runtime.txt

```python
matplotlib
numpy
pycocotools
six
terminaltables
```

**Comment by vansin** [comment]
windows or linux ?

**Comment by fcakyon** [comment]
> windows or linux ?

linux

**Comment by hhaAndroid** [comment]
@fcakyon Thank your feedback. Can you check the reason why pycocotools was not successfully installed?

**Comment by fcakyon** [comment]
> @fcakyon Strange, `pycocotools` should be automatically installed when mmdet is installed,
> 
> https://github.com/open-mmlab/mmdetection/blob/3.x/requirements/runtime.txt
> 
> ```python
> matplotlib
> numpy
> pycocotools
> six
> terminaltables
> ```

Same env includes pycocotools, actually: `pycocotools               2.0.2                    pypi_0    pypi`

Maybe I have some other issue.

**Comment by hhaAndroid** [comment]
@fcakyon Because in detection tasks, **pycocotools** is generally installed by default. Do you think it is necessary to make it optional?

**Comment by fcakyon** [comment]
> @fcakyon Because in detection tasks, **pycocotools** is generally installed by default. Do you think it is necessary to make it optional?

In the [ultralytics/yolov5](https://github.com/ultralytics/yolov5), pycocotools is optional and it is required when training or validating a model. For inference, there is no need for compiling the C code required for pycocotools.

**Comment by fcakyon** [comment]
> @fcakyon Strange, `pycocotools` should be automatically installed when mmdet is installed,
> 
> https://github.com/open-mmlab/mmdetection/blob/3.x/requirements/runtime.txt
> 
> ```python
> matplotlib
> numpy
> pycocotools
> six
> terminaltables
> ```

Uninstalling and reinstalling pycocotools fixed the error.

**Comment by hhaAndroid** [comment]
> > @fcakyon Because in detection tasks, **pycocotools** is generally installed by default. Do you think it is necessary to make it optional?
> 
> In the [ultralytics/yolov5](https://github.com/ultralytics/yolov5), pycocotools is optional and it is required when training or validating a model. For inference, there is no need for compiling the C code required for pycocotools.

Ok， This will involve mmdet code modification. I'll give feedback and discuss.

**Comment by fcakyon** [comment]
Then we can close this issue and continue from the one you created :+1:
