### ISSUE TITLE
Try different method to fusion feature map.

### ISSUE THREAD

**Issue by LiYan0306** [open-mmlab/mmyolo#236]
### What is the problem this feature will solve?

Maybe a new method to fusion feature map will enhance the performance of yolo.
In the course of my research on yolo, I found a problem: for example, in the yolov5 network, why is the feature map used for feature fusion output from the backbone part of these positions, but not the other positions? Or why did the other networks that used feature fusion choose to output feature maps from those locations and not others? 

### What is the feature you are proposing to solve the problem?

Would it be better to use the feature maps for feature fusion at other locations instead?

**Comment by hhaAndroid** [comment]
@LiYan0306 This is indeed a question worth discussing, and I guess this is a general paradigm. Most FPN feature fusion methods use these outputs. Do you have any good opinions?
