### ISSUE TITLE
查询模块脚本

### ISSUE THREAD

**Issue by Zheng-LinXiao** [open-mmlab/mmyolo#247]
### What is the problem this feature will solve?

例如，想看下mmocr里面实现了哪些transformer，以方便我调用。

### What is the feature you are proposing to solve the problem?

在OpenMMLab库里面的模块中，根据需求进行查询，并打印出结果。

**Comment by RangiLyu** [comment]
Try to use this script:

```python
from mmengine.registry.utils import count_registered_modules
from mmocr.utils import register_all_modules  # or from mmyolo/mmdet/mmcls .utils import register_all_modules to count other repo's modules

register_all_modules()
count_registered_modules(save_path='./', verbose=True)
```

 The results will be saved to ./modules_statistic_results.json

**Comment by Zheng-LinXiao** [comment]
Thank you very much for your reply, which is very helpful to me.

**Comment by hhaAndroid** [comment]
Resolved https://github.com/open-mmlab/mmyolo/pull/559
