### ISSUE TITLE
关于模型部署的问题

### ISSUE THREAD

**Issue by VJoer** [open-mmlab/mmyolo#256]
mmyolo 环境依赖mmcv>=2.0.0rc1,<2.1.0，但是mmdeploy 环境依赖mmcv-full，目前mmcv-full最新版本为1.7.0。
使用mmdeploy进行torch2onnx时会提示mmcv版本过低，卸载mmcv-full==1.7.0用mmcv==2.0.0rc1，mmdeploy又会报错No module named 'mmcv.utils'。请问mmcv这个包依赖要怎么解决？

**Comment by hhaAndroid** [comment]
请使用 mmdeploy dev 1.x 分支
