### ISSUE TITLE
could not find the checkpoint of yolov7

### ISSUE THREAD

**Issue by chunxt** [open-mmlab/mmyolo#283]
### Model/Dataset description

Could you offer me the checkpoint of yolov7?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by xin-li-67** [comment]
Hi @chunxt , 

Thanks for being interested in MMYOLO. MMYOLO's YOLOv7 is still under development as [#PR243](https://github.com/open-mmlab/mmyolo/pull/243) shows. The checkpoints will be released by the end of this month.

**Comment by chunxt** [comment]
> Hi @chunxt ,
> 
> Thanks for being interested in MMYOLO. MMYOLO's YOLOv7 is still under development as [#PR243](https://github.com/open-mmlab/mmyolo/pull/243) shows. The checkpoints will be released by the end of this month.

Tks, I am looking forward to this experiment. And I will give it continuous attention.
