### ISSUE TITLE
[Bug in Docs] invalid url in user_guides/config

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmyolo#299]
### 📚 The doc issue

[optimizer wrapper tutorial](https://mmengine.readthedocs.io/en/latest/tutorials/optimizer.html) url [in this md file](https://github.com/open-mmlab/mmyolo/blob/main/docs/en/user_guides/config.md#optimization-config) is invalid. 

Can you please tell me where should I check to use custom learning rate and schedule in mmyolo models?

**Comment by hhaAndroid** [comment]
@fcakyon Thank you.

**Comment by RangeKing** [comment]
Fixed in https://github.com/open-mmlab/mmyolo/pull/303
