### ISSUE TITLE
About adding knowledge distillation code？

### ISSUE THREAD

**Issue by wangtao2668129173** [open-mmlab/mmyolo#320]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

we build  a distiller model, inherit singlestagedetector/basedetector， loading teacher model and student model at the same time will report an error.  It looks like the runner in mmengine（mmcv does not have this problem）. What should I do?

### Environment

torch=1.8.0
torchvision=0.9.0
mmcv=2.0.0
mmdet=3.0.0
mmengine:0.3.1

**Comment by RangeKing** [comment]
Could you please provide detailed information about the error?

**Comment by wangtao2668129173** [comment]
yapf.yaplib.error.YapfError:<unknow>:136:29:invalid syntax , But I have no problem using a alone MMENGINE_MODELS.build(student_cfg['mode'l])

**Comment by RangeKing** [comment]
> yapf.yaplib.error.YapfError:<unknow>:136:29:invalid syntax , But I have no problem using a alone MMENGINE_MODELS.build(student_cfg['mode'l]) 

Sorry, I am not able to help you based on this information. It's better to open an issue in MMRazor, and please provide more information as you can.
