### ISSUE TITLE
a deploy format convert bug in easydeploy/model/model.py

### ISSUE THREAD

**Issue by eastoc** [open-mmlab/mmyolo#356]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

In easydeploy/model/model.py, a code should be added as follows:
```python
self.backend = backend
```
the entire code is shown as follows:
```python
class DeployModel(nn.Module):

    def __init__(self,
                 baseModel: nn.Module,
                 postprocess_cfg: Optional[ConfigDict] = None):
        super().__init__()
        self.baseModel = baseModel
        self.baseHead = baseModel.bbox_head
        self.__init_sub_attributes()
        detector_type = type(self.baseHead)
        if postprocess_cfg is None:
            pre_top_k = 1000
            keep_top_k = 100
            iou_threshold = 0.65
            score_threshold = 0.25
            backend = 1
        else:
            pre_top_k = postprocess_cfg.get('pre_top_k', 1000)
            keep_top_k = postprocess_cfg.get('keep_top_k', 100)
            iou_threshold = postprocess_cfg.get('iou_threshold', 0.65)
            score_threshold = postprocess_cfg.get('score_threshold', 0.25)
            backend = postprocess_cfg.get('backend', 1)
        self.backend = backend
        self.__switch_deploy()
        self.__dict__.update(locals())
```
the above code have been verified in my environment

If not add the code, the bug will happened like that:
```shell
Loads checkpoint by local backend from path: yolox.pth
^C^CTraceback (most recent call last):
  File "./projects/easydeploy/tools/export.py", line 135, in <module>
    main()
  File "./projects/easydeploy/tools/export.py", line 88, in main
    baseModel = build_model_from_cfg(args.config, args.checkpoint, args.device)
  File "./projects/easydeploy/tools/export.py", line 69, in build_model_from_cfg
    model = init_detector(config_path, checkpoint_path, device=device)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmdet/apis/inference.py", line 80, in init_detector
    model.to(device)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 196, in to
    return super().to(device)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/east_wu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
KeyboardInterrupt
```

### Environment

sys.platform: linux
Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.74
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0+cu111
OpenCV: 4.6.0
MMEngine: 0.3.2
MMCV: 2.0.0rc3
MMDetection: 3.0.0rc4
MMYOLO: 0.2.0+27487fd

### Additional information

1. I have modified this bug

**Comment by hhaAndroid** [comment]
@eastoc Thanks for your feedback, let's check it out.

**Comment by triple-Mu** [comment]
Can you provide a docker image to help find this bug?

**Comment by triple-Mu** [comment]
It stands to reason that self.dict.update(locals()) has changed backend into self.backend.
