### ISSUE TITLE
mmyolo and mmdetection

### ISSUE THREAD

**Issue by chihuajiao** [open-mmlab/mmyolo#364]
### What is the problem this feature will solve?

I want to use the model implemented by mmyolo in the config file that I have implemented through mmdetection. For example, I want to add one of mmyolo's backbones to the complete model defined by mmdetection. Is it possible? What should I do?

### What is the feature you are proposing to solve the problem?

I want to use the model implemented by mmyolo in the config file that I have implemented through mmdetection. For example, I want to add one of mmyolo's backbones to the complete model defined by mmdetection. Is it possible? What should I do?

### What alternatives have you considered?

I want to use the model implemented by mmyolo in the config file that I have implemented through mmdetection. For example, I want to add one of mmyolo's backbones to the complete model defined by mmdetection. Is it possible? What should I do?

**Comment by hhaAndroid** [comment]
@chihuajiao https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/advanced_guides/how_to.md#%E8%B7%A8%E5%BA%93%E4%BD%BF%E7%94%A8%E4%B8%BB%E5%B9%B2%E7%BD%91%E7%BB%9C

**Comment by zsy7532** [comment]
> https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/advanced_guides/how_to.md#%E8%B7%A8%E5%BA%93%E4%BD%BF%E7%94%A8%E4%B8%BB%E5%B9%B2%E7%BD%91%E7%BB%9C

Hello, I want to know when to update the cross-library_application.md?
