### ISSUE TITLE
AssertionError (assert points.size(-1) == 2) when yolov6 from training to val

### ISSUE THREAD

**Issue by LEFTeyex** [open-mmlab/mmyolo#373]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Sometimes when yolov6 moves from the training to the val, will raise AssertionError(corresponding to code `assert points.size(-1) == 2` in distance_point_bbox_coder.py line 46). 
As follows:
![1671107288024](https://user-images.githubusercontent.com/76982584/207859214-b0f3ec6b-eb76-423a-9efb-2a3310e4c988.png)

### Environment

```
CUDA_VERSION=11.3
CUDNN_VERSION=8.2.0
Python 3.8.15
PyTorch 1.11.0+cu113
OpenCV 4.5.5
MMEngine 0.3.2
MMCV 2.0.0rc3
MMDetection 3.0.0rc4
MMYOLO 0.2.0+536d396
```

### Additional information

I have found the reason.
When yolov6 moves from the training to the val and `featmap_sizes == self.featmap_sizes`, the `self.mlvl_priors` will be used from `loss_by_feat` to `predict_by_feat`. `self.prior_generator.grid_priors(with_stride=True)` in `loss_by_feat` and `self.prior_generator.grid_priors(with_stride=False)` in `predict_by_feat`. The `self.mlvl_priors` from training shape is (..., 4), but the `self.mlvl_priors` generate in val shape is (..., 2).
So, `assert points.size(-1) == 2` raise AssertionError.

**In `YOLOv6Head.loss_by_feat` method**
```
# If the shape does not equal, generate new one
if current_featmap_sizes != self.featmap_sizes:
    self.featmap_sizes = current_featmap_sizes
    self.mlvl_priors = self.prior_generator.grid_priors(
        self.featmap_sizes,
        dtype=cls_scores[0].dtype,
        device=cls_scores[0].device,
        with_stride=True)  ###### with_stride=True
    self.num_level_priors = [len(n) for n in self.mlvl_priors]
    self.flatten_priors = torch.cat(self.mlvl_priors, dim=0)
    self.stride_tensor = self.flatten_priors[..., [2]]
```

**In `YOLOv5Head.predict_by_feat` method**
```
# If the shape does not change, use the previous mlvl_priors
if featmap_sizes != self.featmap_sizes:  ###### when featmap_sizes == self.featmap_sizes
    self.mlvl_priors = self.prior_generator.grid_priors(
        featmap_sizes,
        dtype=cls_scores[0].dtype,
        device=cls_scores[0].device)  ###### with_stride=False
    self.featmap_sizes = featmap_sizes
flatten_priors = torch.cat(self.mlvl_priors)  ###### self.mlvl_priors from training shape is (..., 4) but need (..., 2) here
mlvl_strides = [
    flatten_priors.new_full(
        (featmap_size.numel() * self.num_base_priors, ), stride) for
    featmap_size, stride in zip(featmap_sizes, self.featmap_strides)
]
flatten_stride = torch.cat(mlvl_strides)
# flatten cls_scores, bbox_preds and objectness
flatten_cls_scores = [
    cls_score.permute(0, 2, 3, 1).reshape(num_imgs, -1,
                                          self.num_classes)
    for cls_score in cls_scores
]
flatten_bbox_preds = [
    bbox_pred.permute(0, 2, 3, 1).reshape(num_imgs, -1, 4)
    for bbox_pred in bbox_preds
]
flatten_cls_scores = torch.cat(flatten_cls_scores, dim=1).sigmoid()
flatten_bbox_preds = torch.cat(flatten_bbox_preds, dim=1)
flatten_decoded_bboxes = self.bbox_coder.decode(   ###### raise AssertionError
    flatten_priors[None], flatten_bbox_preds, flatten_stride)
```

**Comment by RangeKing** [comment]
Thanks for your feedback. We'll fix this soon.

**Comment by PeterH0323** [comment]
Hi @LEFTeyex 
Thx for the feedback, can you give us your code latest git log by using:
```bash
git log
```

**Comment by LEFTeyex** [comment]
Hello @PeterH0323
I use mmyolo by `mim install "mmyolo==0.2.0"`.

**Comment by PeterH0323** [comment]
Close as fix
