### ISSUE TITLE
yolov7的test_pipeline疑似存在bug

### ISSUE THREAD

**Issue by tang576225574** [open-mmlab/mmyolo#379]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

transforms.py文件：
class LetterResize:
    def _resize_img(self, results: dict):
        ...
        scale_factor = (ratio[1], ratio[0])  # mmcv scale factor is (w, h)   # 210行

        if 'scale_factor' in results:
            results['scale_factor'] = (results['scale_factor'][0] *                  # 213行
                                                   scale_factor[0],
                                                   results['scale_factor'][1] *
                                                   scale_factor[1])
        else:
            results['scale_factor'] = scale_factor

    def _resize_bboxes(self, results: dict):
        ...
        results['gt_bboxes'].rescale_(results['scale_factor'])   # 283行

前提：在yolo v7中，test_pipeline依次执行YOLOv5KeepRatioResize和LetterResize
问题定位：
1，当经过“YOLOv5KeepRatioResize”操作之后，"scale_factor"这个key已存在于results中，因此“LetterResize”操作执行213行代码：修改results["scale_factor"]为原来的results["scale_factor"]与新计算的scale_factor的乘积。
2，直到上面的操作，逻辑上均没有问题，results["scale_factor"]的值也正确，代表的是整个pipeline对图像缩放的因数。但是，在随后的283行，作者使用了这个新计算的results["scale_factor"]缩放因数来更新gt_bboxes参数，这似乎是不对的，因为gt_bboxes在上一个pipeline（也就是YOLOv5KeepRatioResize）已经被更新过一次，因此只需要使用本pipeline（也就是LetterResize）的缩放因数去更新gt_bboxes就可以了，无需用整个pipeline的缩放因数；如果再使用整个pipeline的缩放因数更新gt_bboxes，那么gt_bboxes将会被多缩放一次，gt_bboxes的值反而不对。
3，正确的做法应该是：在_resize_img时不更新results里面的scale_factor而只是记录新计算的scale_factor，然后用这个新计算的scale_factor更新gt_bboxes和gt_mask等，最后更新完所有数据后再执行213行代码更新results['scale_factor']。

### Environment

python train.py configs/yolov7/yolov7_tiny_syncbn_fast_8x16b-300e_coco.py

**Comment by hhaAndroid** [comment]
@tang576225574 非常感谢你的反馈。确实是错误的。因为现在这个函数只是用于 test，并且是在这个函数后才加载标注，所以现在 MMYOLO 代码功能都是正常的，一直没有发现。 你有空可以修复下？感谢

**Comment by tang576225574** [comment]
好啊，可以啊，是我提交一个修改后的合并请求吗？



---原始邮件---
发件人: "Haian ***@***.***&gt;
发送时间: 2022年12月16日(周五) 晚上7:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmyolo] yolov7的test_pipeline疑似存在bug (Issue #379)




 
@tang576225574 非常感谢你的反馈。确实是错误的。因为现在这个函数只是用于 test，并且是在这个函数后才加载标注，所以现在 MMYOLO 代码功能都是正常的，一直没有发现。 你有空可以修复下？感谢

**Comment by hhaAndroid** [comment]
> 

对的，往 Dev 分支提PR

**Comment by hhaAndroid** [comment]
> 好啊，可以啊，是我提交一个修改后的合并请求吗？
> […](#)
> ---原始邮件--- 发件人: "Haian ***@***.***&gt; 发送时间: 2022年12月16日(周五) 晚上7:43 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [open-mmlab/mmyolo] yolov7的test_pipeline疑似存在bug (Issue #379) @tang576225574 非常感谢你的反馈。确实是错误的。因为现在这个函数只是用于 test，并且是在这个函数后才加载标注，所以现在 MMYOLO 代码功能都是正常的，一直没有发现。 你有空可以修复下？感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

对的，往 dev 分支提PR

**Comment by tang576225574** [comment]
已提交修复pr #387
