### ISSUE TITLE
Can not right load the category if blank in it

### ISSUE THREAD

**Issue by wang-tf** [open-mmlab/mmyolo#390]
https://github.com/open-mmlab/mmyolo/blob/27487fd587398348d59eb8c40af740cabee6b7fe/tools/dataset_converters/labelme2coco.py#L277

**Comment by PeterH0323** [comment]
Hi @wang-tf 
Thx for the issue.
We don’t suggest users set a category as ‘ ’. If the user has this situation, we will assert and then show a message to advice user to rename it as `blank` or `None`.

**Comment by wang-tf** [comment]
In my case, there are some categories like `Category One`.

**Comment by PeterH0323** [comment]
You can use like `Category-One`

**Comment by wang-tf** [comment]
> You can use like `Category-One`

OK. That's a good way.
