### ISSUE TITLE
where is multi-scale train ?

### ISSUE THREAD

**Issue by www516717402** [open-mmlab/mmyolo#414]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

1. Where is multi-scale train method in mmyolo?

2. when will release new version 0.3.0 ?

### Environment

version 0.2.0

### Expected results

None

### Additional information

None

**Comment by hhaAndroid** [comment]
@www516717402 If the size of the images output by the pipeline data are different, then it is multi-scale training itself. Can you elaborate on the requirements?

**Comment by www516717402** [comment]
I use mmdet 2.x version however first times use mmyolo. 
1. multi-scale train in mmdetection YOLOX
https://github.com/open-mmlab/mmdetection/blob/c02c63b59b879d1f931bf2fe5fd52f7528d9f102/mmdet/models/detectors/yolox.py#L105
2. multi-scale train in mmdetection YOLOV5
https://github.com/ultralytics/yolov5/blob/65071da7181e2ede9d3514f20c88e6bd646af07c/train.py#L300

And never see similar operate in MMYOLO-YOLOV5

**Comment by hhaAndroid** [comment]
@www516717402 In openmmlab 2.0 YOLOX, multiscale training has been implemented by BatchSyncRandomResize in DetDataPreprocessor. This is a new design and you can also call this module directly in MMYOLO to implement multiscale training. The official multiscale training approach in YOLOv5 is similar to BatchSyncRandomResize, but without the synchronization feature. If you want a multi-scale training exactly like yolov5, you can add a new `batch_augments`. 

Please refer this 
- https://github.com/open-mmlab/mmdetection/blob/3.x/mmdet/models/data_preprocessors/data_preprocessor.py#L201
- https://github.com/open-mmlab/mmdetection/blob/3.x/mmdet/models/data_preprocessors/data_preprocessor.py#L558

**Comment by www516717402** [comment]
Great help. Why not use multi-scale train in MMYOLO-YOLOV5 and it will influence mAP?

**Comment by hhaAndroid** [comment]
@www516717402 Multi-scale training can certainly improve performance, but we are hoping to align with the official yolov5 performance.

**Comment by www516717402** [comment]
Thanks again.
