### ISSUE TITLE
 _from_which_layer = _from_which_layer[fg_mask_inboxes] RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by 52THANOS** [open-mmlab/mmyolo#437]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

 _from_which_layer = _from_which_layer[fg_mask_inboxes]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### Environment

pip

**Comment by hhaAndroid** [comment]
@52THANOS The dev branch has fixed it.

**Comment by 52THANOS** [comment]
i have another issue on batch_yolov7_assigner.py file
