### ISSUE TITLE
When I run demo/featmap_vis_demo.py, the feature maps, classes and the detection boxes appear together. Is there any way not to display the calsses and detection boxes? I just want him to show the feature maps

### ISSUE THREAD

**Issue by ZZY-666** [open-mmlab/mmyolo#465]
### What is the problem this feature will solve?

The feature maps will be  more beautiful.

### What is the feature you are proposing to solve the problem?

Remove the detection boxes

**Comment by RangeKing** [comment]
@ZZY-666, you can add `--score-thr 1` when running `demo/featmap_vis_demo.py`. It'll remove all the detection boxes.

**Comment by ZZY-666** [comment]
Thank you for your answer. Another problem, if I have trained the model on my own dataset such road traffic, can I directly run demo/featmap_vis_demo.py to generate the feature maps of cars?

**Comment by RangeKing** [comment]
I guess you want the same feature mentioned in https://github.com/open-mmlab/mmyolo/issues/463.
https://github.com/open-mmlab/mmyolo/issues/463#issuecomment-1381341676

**Comment by ZZY-666** [comment]
No, what I care about is whether I can use demo/featmap_vis_demo.py to visualize the feature maps on my dataset. Thank you for your answer!

**Comment by RangeKing** [comment]
> No, what I care about is whether I can use demo/featmap_vis_demo.py to visualize the feature maps on my dataset. Thank you for your answer!

Of course, you can.

**Comment by ZZY-666** [comment]
Once again, I would like to express my admiration for the strength of MMYOLO. If I run "python demo/featmap_vis_demo.py demo/demo.jpg configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py mmyolov8s.pth --channel-reductio squeeze_mean" to visualize the model trained on the my own data set. In addition to replacing with my ownweight, what changes should I make to “yolov8_s_syncbn_fast_8xb16-500e_coco.py”?

**Comment by ZZY-666** [comment]
Thank you very much for your patience, and I have one last question: How to train MM-YOLO with mult-devices? 
Looking forward to reply！

**Comment by RangeKing** [comment]
> Thank you very much for your patience, and I have one last question: How to train MM-YOLO with mult-devices? Looking forward to reply！

Refer to MMDet-3.x document, https://mmdetection.readthedocs.io/en/3.x/user_guides/train.html

**Comment by ZZY-666** [comment]
Thank you very much for your high-quality answers!
