### ISSUE TITLE
给MMYOLO添加model zoo中的模型指标对比图

### ISSUE THREAD

**Issue by isLinXu** [open-mmlab/mmyolo#476]
### What is the problem this feature will solve?

任务目标：给MMYOLO绘制相关网络指标参数对比图;

### What is the feature you are proposing to solve the problem?

需求场景：用于学术论文及实验结果的对比
功能描述：事实上目前绘图程序已经基本实现在这个[仓库](https://github.com/isLinXu/model-metrics-plot)中，后续更多模型指标参数可以一起整理验证，会以PR的形式进行提交更新
另外：给PaddleYOLO绘制的图形在这个[PR](https://github.com/PaddlePaddle/PaddleYOLO/pull/81)链接下，目前已经被merge采用。

### What alternatives have you considered?

想要问一下，相关负责人是否有兴趣一起来做MMYOLO类似的插图，还有关于这个[仓库](https://github.com/isLinXu/model-metrics-plot)是否能以mmplot去命名，期待回复，谢谢。

**Comment by hhaAndroid** [comment]
@isLinXu 谢谢你的关注和非常好看的对比图。MMYOLO 正在设计新的对比和评测指标，现在还没有想好 model zoo 里面到底应该绘制哪些图。等我们确定了具体形式，到时候欢迎你一起来绘制好看的图表。期待你的贡献！

**Comment by isLinXu** [comment]
好的，先等一波后续，新年快乐

**Comment by hhaAndroid** [comment]
@isLinXu 我们准备绘制曲线图？你是否想帮忙提一个 PR?

**Comment by isLinXu** [comment]
可以的
