### ISSUE TITLE
v5 v6 x v8 have the network diagram, but v7 does not. can you draw a structure diagram of v7？

### ISSUE THREAD

**Issue by Xuchangsheng1** [open-mmlab/mmyolo#491]
### What is the problem this feature will solve?

v5 v6 x v8 have the network diagram, but v7 does not. can you draw a structure diagram of v7？

### What is the feature you are proposing to solve the problem?

structure diagram

**Comment by hhaAndroid** [comment]
@Xuchangsheng1 Thank you very much for your feedback, it is already being processed.

**Comment by hhaAndroid** [comment]
@Xuchangsheng1 resloved  https://github.com/open-mmlab/mmyolo/tree/dev/configs/yolov7
