### ISSUE TITLE
calculated fps

### ISSUE THREAD

**Issue by hanknewbird** [open-mmlab/mmyolo#514]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

There was an error when mmyolo calculated fps. I can't find the corresponding situation in the document

Failed to pop up and load the model

![image](https://user-images.githubusercontent.com/69323595/216824559-31edd1ab-e947-49fd-b0c1-67b763b589aa.png)

### Environment

The environment has been running through mmdetection and mmsegmentation. It should be OK

**Comment by hhaAndroid** [comment]
@hanknewbird I don't see the error message, can you elaborate on the error message？
