### ISSUE TITLE
can you provide the convert config of yolov7-e6e

### ISSUE THREAD

**Issue by zero0kiriyu** [open-mmlab/mmyolo#521]
### What is the problem this feature will solve?

Current yolov7 weight convert script does not has the config of yolov7-e6e

### What is the feature you are proposing to solve the problem?

Provide the convert config of yolov7-e6e

**Comment by hhaAndroid** [comment]
@zero0kiriyu OK

**Comment by hhaAndroid** [comment]
Resolved by https://github.com/open-mmlab/mmyolo/pull/570
