### ISSUE TITLE
Extend assigner visualization tool to anchor-free method

### ISSUE THREAD

**Issue by zero0kiriyu** [open-mmlab/mmyolo#522]
### What is the problem this feature will solve?

visualize the label assignment result of anchor free head

### What is the feature you are proposing to solve the problem?

visualize the label assignment result of anchor free head

**Comment by hhaAndroid** [comment]
@zero0kiriyu Thank you for your attention, we are already developing.

**Comment by hhaAndroid** [comment]
@zero0kiriyu Resolved https://github.com/open-mmlab/mmyolo/pull/528
