### ISSUE TITLE
On error reporting in yolov 8 training

### ISSUE THREAD

**Issue by majintao1994** [open-mmlab/mmyolo#523]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

In training, after one iteration, errors are reported in the evaluation stage and training is interrupted
as follow:
Exception in thread Thread-2:
Traceback (most recent call last):
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/threading.py",line 932, in _bootstrap_inner
    self.run()
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
 File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)
02/07 14:29:49 - mmengine - INFO - Exp name: yolo8_20230207_142529
Traceback (most recent call last):
File "/home/work/YOLO_presearch/mmyolo-main/tools/train.py", line 119, in <module>
main()
  File "/home/work/YOLO_presearch/mmyolo-main/tools/train.py",line 115, in main
    runner.train()
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1684, in train
    model = self.train_loop.run()  # type: ignore
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/mmengine/runner/loops.py"
, line 105, in run_epoch  for idx, data_batch in enumerate(self.dataloader):
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 349, in __iter__
    self._iterator._reset(self)
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 852, in _reset
    data = self._get_data()
File "/home/ty/anaconda3/envs/mmdet3/lib/python3.8/site-packages/torch/utils/data/dataloader.py",line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly

### Environment

Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: GeForce RTX 2070
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.13
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
 - C++ Version: 201402
 - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0(Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  -  CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG 
  - TorchVision: 0.8.2+cu101
OpenCV: 4.6.0
MMEngine: 0.3.2
MMCV: 2.0.0rc1
MMDetection: 3.0.0rc5
MMYOLO: 0.4.0+

### Additional information

_base_ = '../_base_/default_runtime.py'

# dataset settings
data_root = '/home/work/YOLO_presearch/20230130/'
dataset_type = 'YOLOv5CocoDataset'
# parameters that often need to be modified
num_classes = 23
img_scale = (640, 640)  # height, width
deepen_factor = 0.33
widen_factor = 0.5
max_epochs = 500
save_epoch_intervals = 10
train_batch_size_per_gpu = 16
train_num_workers = 8
val_batch_size_per_gpu = 1
val_num_workers = 2

# persistent_workers must be False if num_workers is 0.

persistent_workers = True
strides = [8, 16, 32]
num_det_layers = 3
last_stage_out_channels = 1024

# Base learning rate for optim_wrapper
base_lr = 0.0001
lr_factor = 0.0001
env_cfg = dict(cudnn_benchmark=True)
model = dict(
    type='YOLODetector',
    data_preprocessor=dict(
        type='YOLOv5DetDataPreprocessor',
        mean=[0., 0., 0.],
        std=[255., 255., 255.],
        bgr_to_rgb=True),
    backbone=dict(
        type='YOLOv8CSPDarknet',
        arch='P5',
        last_stage_out_channels=last_stage_out_channels,
        deepen_factor=deepen_factor,
        widen_factor=widen_factor,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    neck=dict(
        type='YOLOv8PAFPN',
        deepen_factor=deepen_factor,
        widen_factor=widen_factor,
        in_channels=[256, 512, last_stage_out_channels],
        out_channels=[256, 512, last_stage_out_channels],
        num_csp_blocks=3,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    bbox_head=dict(
         type='YOLOv8Head',
        head_module=dict(
        type='YOLOv8HeadModule',
        num_classes=num_classes,
        in_channels=[256, 512, last_stage_out_channels],
        widen_factor=widen_factor,
        reg_max=16,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True),
        featmap_strides=[8, 16, 32]),
    prior_generator=dict(    
        type='mmdet.MlvlPointGenerator', offset=0.5, strides=[8, 16, 32]),
     bbox_coder=dict(type='DistancePointBBoxCoder'),
     loss_cls=dict(
           type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
           reduction='none',
            loss_weight=0.5),
     loss_bbox=dict(
        type='IoULoss',
        iou_mode='ciou',
        bbox_format='xyxy',
        reduction='sum',
        loss_weight=7.5,
        return_iou=False),
     loss_dfl=dict(
            type='mmdet.DistributionFocalLoss',
            reduction='mean',
            loss_weight=1.5 / 4)),
    train_cfg=dict(
        assigner=dict(
            type='BatchTaskAlignedAssigner',
            num_classes=num_classes,
            use_ciou=True,
            topk=10,
            alpha=0.5,
             beta=6.0,
            eps=1e-9)),
    test_cfg=dict(
          multi_label=True,
        nms_pre=30000,
        score_thr=0.001,
        nms=dict(type='nms', iou_threshold=0.7),
        max_per_img=300))
albu_train_transform = [
    dict(type='Blur', p=0.01),
    dict(type='MedianBlur', p=0.01),
    dict(type='ToGray', p=0.01),
    dict(type='CLAHE', p=0.01)
]
pre_transform = [
    dict(type='LoadImageFromFile', file_client_args=_base_.file_client_args),
    dict(type='LoadAnnotations', with_bbox=True)
]

last_transform = [
    dict(
        type='mmdet.Albu',
        transforms=albu_train_transform,
        bbox_params=dict(
        type='BboxParams',
        format='pascal_voc',
        label_fields=['gt_bboxes_labels', 'gt_ignore_flags']),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        }),
    dict(type='YOLOv5HSVRandomAug'),
    dict(type='mmdet.RandomFlip', prob=0.5),
    dict(
        type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                         'flip_direction'))
]
train_pipeline = [
*pre_transform,
dict(
        type='Mosaic',
        img_scale=img_scale,
        pad_val=114.0,
        pre_transform=pre_transform),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
         scaling_ratio_range=(0.5, 1.5),
        max_aspect_ratio=100,
       border=(-img_scale[0] // 2, -img_scale[1] // 2),
        border_val=(114, 114, 114)),

    *last_transform
]
train_pipeline_stage2 = [
    *pre_transform,
     dict(type='YOLOv5KeepRatioResize', scale=img_scale),
    dict(
        type='LetterResize',
        scale=img_scale,
        allow_scale_up=True,
         pad_val=dict(img=114.0)),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        scaling_ratio_range=(0.5, 1.5),
        max_aspect_ratio=100,
        border_val=(114, 114, 114)), *last_transform
        ]
train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    persistent_workers=persistent_workers,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
   collate_fn=dict(type='yolov5_collate'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
         ann_file='annotations/instances_train2017.json',
         data_prefix=dict(img='train2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        pipeline=train_pipeline))

test_pipeline = [
        dict(type='LoadImageFromFile', file_client_args=_base_.file_client_args),
        dict(type='YOLOv5KeepRatioResize', scale=img_scale),
        dict(
             type='LetterResize',
             scale=img_scale,
            allow_scale_up=False,
            pad_val=dict(img=114)),
       dict(type='LoadAnnotations', with_bbox=True, _scope_='mmdet'),
       dict(
        type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                      'scale_factor', 'pad_param'))
]
val_dataloader = dict(
    batch_size=val_batch_size_per_gpu,
    num_workers=val_num_workers,
    persistent_workers=persistent_workers,
     pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
     dataset=dict(
        type=dataset_type,
        data_root=data_root,
        test_mode=True,
        data_prefix=dict(img='val2017/'),
        ann_file='annotations/instances_val2017.json',
        pipeline=test_pipeline,
         batch_shapes_cfg=batch_shapes_cfg))
test_dataloader = val_dataloader
param_scheduler = None
optim_wrapper = dict(
    type='OptimWrapper',
    clip_grad=dict(max_norm=10.0),
    optimizer=dict(
        type='SGD',
        lr=base_lr,
        momentum=0.937,
        weight_decay=0.0005,
        nesterov=True,
        batch_size_per_gpu=train_batch_size_per_gpu),
    constructor='YOLOv5OptimizerConstructor')
default_hooks = dict(
    param_scheduler=dict(
         type='YOLOv5ParamSchedulerHook',
        scheduler_type='linear',
        lr_factor=lr_factor,
         max_epochs=max_epochs),
    checkpoint=dict(
         type='CheckpointHook',
         interval=save_epoch_intervals,
        save_best='auto',
        max_keep_ckpts=2))
custom_hooks = [
    dict(
        type='EMAHook',
        ema_type='ExpMomentumEMA',
        momentum=0.0001,
        update_buffers=True,
        strict_load=False,
        priority=49),
    dict(
         type='mmdet.PipelineSwitchHook',
        switch_epoch=max_epochs - 10,
        switch_pipeline=train_pipeline_stage2)
]
val_evaluator = dict(
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file=data_root + 'annotations/instances_val2017.json',
    metric='bbox')
test_evaluator = val_evaluator
train_cfg = dict(
    type='EpochBasedTrainLoop',
    max_epochs=max_epochs,
    val_interval=save_epoch_intervals,
    dynamic_intervals=[(max_epochs - 10, 1)])
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

**Comment by hhaAndroid** [comment]
@majintao1994 This is a known problem of pytorch1.7, you can change to a higher version or turn off `pin_memory`

**Comment by majintao1994** [comment]
think you.I had turned off pin_memory,and it can work now
