### ISSUE TITLE
How could I debug when I try implement some new features into mmyolo?

### ISSUE THREAD

**Issue by lanqz7766** [open-mmlab/mmyolo#524]
### What is the problem this feature will solve?

Hi, I have been used mmdetection, and it supports print out some information during training by adding the 
logger.info(f'the variable I want to check: {x}') from mmdet/utils/logger, get_logger()
or print(f'the variable I want to check: {x}'). 

However, when I try add something similar to model/detector/yolo_detector.py, it won't print out anything I expected. I also can not call get_logger(), so I copy and implement those from mmcv, but it still does not work.

I guess that it do not have "TextLoggerHook" in mmyolo?

### What is the feature you are proposing to solve the problem?

I hope we can add TextLogHook like MMdetection that help to debug when someone implements their own code.

Alternatively, is there a quick way for me to output text log in mmyolo?

**Comment by hhaAndroid** [comment]
@lanqz7766 Thank you for your attention. mmyolo is based on the mmdet 3.x branch. It is part of openmmlab2.0. The `TextLogHook` you mentioned is the module of mmdet 2.x and openmmlab1.0. You can carefully read the tutorials or videos we provide.
