### ISSUE TITLE
./projects/easydeploy/tools/image-demo.py 验证 rtmdet 输出结果不正确。

### ISSUE THREAD

**Issue by wanyne-yyds** [open-mmlab/mmyolo#533]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

**我使用官方提供的 rtmdet config 与 model 转换成 onnx model 成功，但在输出的结果并不准确。后又尝试了 YOLOX-S，PPYOLO-S，YOLOV5-S 这个几个模型，用的同样是官方提供的 config 与 model，这几个结果都是对的。**

```shell
// 转模型脚本
python ./projects/easydeploy/tools/export.py \
	/mmyolo/code/configs/rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py \
	--checkpoint /mmyolo/code/work_dir/rtmdet_l_syncbn_fast_8xb32-300e_coco_20230102_135928-ee3abdc4.pth \
	--work-dir /mmyolo/code/work_dir/rtmdet_tiny_syncbn_fast_8xb32-300e_coco \
    --img-size 640 640 \
    --batch 1 \
    --device cpu \
    --simplify \
	--opset 11 \
	--backend 1 \
	--pre-topk 1000 \
	--keep-topk 100 \
	--iou-threshold 0.65 \
	--score-threshold 0.25


// 运行脚本
python projects/easydeploy/tools/image-demo.py \
    /mmyolo/code/demo/demo.jpg /mmyolo/code/configs/rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py \
    /mmyolo/code/work_dir/rtmdet_tiny_syncbn_fast_8xb32-300e_coco/end2end.onnx \
    --out-dir /mmyolo/code/work_dir/pred \
    --device cuda:1
```
**检测结果如下：**
![image](https://user-images.githubusercontent.com/43132407/217466716-cac61503-15b8-42c2-a063-d1d1f725e2ef.png)
![image](https://user-images.githubusercontent.com/43132407/217467341-8fd25e92-342c-436a-8441-35506e379bb5.png)

### Environment

**使用官方提供的 Dockerfile 创建的 docker 环境**

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.7.0
MMEngine: 0.4.0
MMCV: 2.0.0rc4
MMDetection: 3.0.0rc5
MMYOLO: 0.4.0+e62c8c4

### Additional information

是否会是rtmdet解码不正确，本人能力有限，无法排查出来，烦请帮忙查看一下，谢谢

**Comment by hhaAndroid** [comment]
@wanyne-yyds Thanks for your feedback, we have fixed it in dev branch
