### ISSUE TITLE
可以制作类似mmdetetion中tools/analysis_tools/confusion_matrix.py的混淆矩阵吗

### ISSUE THREAD

**Issue by yaofanji** [open-mmlab/mmyolo#534]
可以制作类似mmdetetion中tools/analysis_tools/confusion_matrix.py的混淆矩阵吗

**Comment by hhaAndroid** [comment]
@yaofanji OK

**Comment by paihuai0** [comment]
> @yaofanji OK

mmdet3.x have tools/analysis_tools/confusion_matrix.py

**Comment by ibrahim014** [comment]
How can we use confusion_matrix.py in mmyolo?

**Comment by hhaAndroid** [comment]
Resolved https://github.com/open-mmlab/mmyolo/pull/572
