### ISSUE TITLE
yolov8中df loss的loss weight为什么除以4.

### ISSUE THREAD

**Issue by CangHaiQingYue** [open-mmlab/mmyolo#564]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

如题

### Environment

如题

**Comment by hhaAndroid** [comment]
@Nioolek

**Comment by Nioolek** [comment]
实现不太一样。原版dfl的实现是使用(n,4)维度计算，然后求mean。
mmdet上的实现是在(n*4,)上计算，所以要除以4

**Comment by CangHaiQingYue** [comment]
> 实现不太一样。原版dfl的实现是使用(n,4)维度计算，然后求mean。 mmdet上的实现是在(n*4,)上计算，所以要除以4

好的，谢谢大佬！
