### ISSUE TITLE
Export model without NMS

### ISSUE THREAD

**Issue by LingCoder1997** [open-mmlab/mmyolo#567]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

Hi! I have trained my yolov7-x model on the customed dataset. Now I would like  to test my model using my own postprocess. However, when I tried to implement my own postprocess code, I found that I need a way to extract the model out of the framework, because the testing process has been wrapped up like a onion, which can only be editted using the given options in the config file.
After checking the deploying config files, I suppose all the config files provided in the config/deploy directory will keep the NMS process when exporting into the new model due to the setting "model_type=end2end". 

So I wonder if there is a way that I can load the trained model outside the mm-framework in the normal way without nms or if possible, using the mmdeploy converting the model into ONNX or TensorRT format without NMS. 

I am not sure if I descrided the issue clearly, so if there is any question feel free to ask.

### Environment

My env info:
Python 3.6.9
Pytorch 1.8
Torchvision 0.9.0
OpenCV 4.2.0
MMEngine 0.4.0
MMCV: 2.0.0rc3
MMDetection 3.0.0rc5
MMYOLO 0.4.0+

### Expected results

I would expect some coding help on exporting the model or simplified torch model loading.

**Comment by hhaAndroid** [comment]
@LingCoder1997 You can use https://github.com/open-mmlab/mmyolo/blob/dev/projects/easydeploy/README.md. It can support excluding post-processing.

**Comment by LingCoder1997** [comment]
Much appreciate, The code does help! Thank you for the reply
