### ISSUE TITLE
yolov8 训练时显存泄露

### ISSUE THREAD

**Issue by woundenfish** [open-mmlab/mmyolo#569]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

yolov8 训练时显存泄露

### Environment

V

### Expected results

a

**Comment by hhaAndroid** [comment]
@woundenfish Thanks for your feedback, please provide more information.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 7 days.
