### ISSUE TITLE
warning: .save_param_schedulers is true but  self.param_schedulers is None,so skip saving parameter schedulers

### ISSUE THREAD

**Issue by HGD-ai** [open-mmlab/mmyolo#577]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

The following warnings appear during model training:
warning: .save_param_schedulers is true but  self.param_schedulers is None,so skip saving parameter schedulers。
I want to know the reason for this warning and whether the model will reload some parameters such as learning rate when I resume the model?
How can I remove this warning？
Thank you very much for your answer

### Environment

python3.8
cuda11.3
mmengine:0.3.2

**Comment by hhaAndroid** [comment]
@HGD-ai This has no impact on performance, and if you want to remove this warning you can do the following

```shell
default_hooks.checkpoint.save_param_scheduler=False
```

**Comment by HGD-ai** [comment]
Ok, thank you very much for your answer
