### ISSUE TITLE
The GPU memory used during RTMDet training

### ISSUE THREAD

**Issue by laonazzzzz** [open-mmlab/mmyolo#586]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

When I train rtmdet with 4 GPUs(nvidia 1080 with 8g memory),  set the batchsize_per_gpu = 16, the memory occupation to 90%. In the middle of the training, because OOM quit the training。 Is that normal?
What is your hardware and memory used during training.

### Environment

.

**Comment by laonazzzzz** [comment]
By the way, the model is RTMDet-s.

**Comment by hhaAndroid** [comment]
@laonazzzzz this is normal. You can consider reducing bs or `--amp` to turn on amp

**Comment by laonazzzzz** [comment]
@hhaAndroid but yolov5s with the same depth_factor and width_factor, just used 3.8G memory

**Comment by hhaAndroid** [comment]
@laonazzzzz https://github.com/open-mmlab/mmyolo/blob/dev/docs/zh_cn/tutorials/faq.md#rtmdet-%E4%B8%BA%E4%BD%95%E8%AE%AD%E7%BB%83%E6%89%80%E5%8D%A0%E6%98%BE%E5%AD%98%E6%AF%94-yolov5-%E5%A4%9A%E5%BE%88%E5%A4%9A
