### ISSUE TITLE
about deploy mmyolo by mmdeploy

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmyolo#598]
### 📚 The doc issue

i found the document  mention that mmyolo can be deployed by mmdeploy, but i can't found mmdeploy contains mmyolo codebase, how to deploy mmyolo by mmdeploy? 

![image](https://user-images.githubusercontent.com/55951697/221560362-c5b12de0-f563-47ef-bf1f-f1baab93b680.png)

**Comment by hhaAndroid** [comment]
@caj-github Please see https://mmyolo.readthedocs.io/zh_CN/dev/recommended_topics/deploy/index.html

**Comment by caj-github** [comment]
the mmdeploy maybe do not support mmyolo SDK, report a error like this
![image](https://user-images.githubusercontent.com/55951697/221916049-03a3261e-0cfe-4aaf-ab8a-5bfbcf711433.png)

**Comment by xin-li-67** [comment]
> the mmdeploy maybe do not support mmyolo SDK, report a error like this ![image](https://user-images.githubusercontent.com/55951697/221916049-03a3261e-0cfe-4aaf-ab8a-5bfbcf711433.png)

Indeed. MMDeploy SDK only supports the codebase added to MMDEploy.
