### ISSUE TITLE
An error occurred with the confusion_matrix.py in the branch

### ISSUE THREAD

**Issue by yaofanji** [open-mmlab/mmyolo#605]
An error occurred with the confusion_matrix.py in the branch

![confusion_matrix](https://user-images.githubusercontent.com/94046113/221957541-373a3471-5eb8-4cc1-a692-00b044d7faf5.png)

**Comment by hhaAndroid** [comment]
@yaofanji The adaptive display function is not very good, please enlarge the window to solve it

**Comment by yaofanji** [comment]
> 

It's a pity that it still can't be solved
