### ISSUE TITLE
Support wandb resume !!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by zgzhengSEU** [open-mmlab/mmyolo#623]
### What is the problem this feature will solve?

![image](https://user-images.githubusercontent.com/62554593/222869109-816f40ac-714f-45d1-95a9-68d5ea088eaf.png)
I have tried to set resume=True/"allow", id="xxx", allow_val_change=True, but still report this error

### What is the feature you are proposing to solve the problem?

SUPPORT wandb resume !!!!!!!!

**Comment by xin-li-67** [comment]
Hi, actually, this is not an issue to MMYOLO, nor MMEngine which implemented the `VisBackend`. You can see in your error log that MMEngine passed all your wandb init_kwargs to wandb.int() already. You may need to work on wandb documents to see the real reason why `allow_val_change` failed.

**Comment by zgzhengSEU** [comment]
![image](https://user-images.githubusercontent.com/62554593/223007186-3fcc8457-e350-41aa-b843-16205f42fd40.png)
I set allow_val_change=True in MMEngine vis_backend.py。
After I set the option, it stopped prompting this error and successfully ran resume in wandb
