### ISSUE TITLE
/Users/kyanchen/My_Code/DyTiSDet/DyTiSDet_yolo/mmyolo/models/dense_heads/yolov5_head.py:563: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)   batch_targets_scaled = batch_targets_scaled[match_inds]

### ISSUE THREAD

**Issue by KyanChen** [open-mmlab/mmyolo#626]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

/Users/kyanchen/My_Code/DyTiSDet/DyTiSDet_yolo/mmyolo/models/dense_heads/yolov5_head.py:563: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  batch_targets_scaled = batch_targets_scaled[match_inds]

### Environment

MAC MPS

**Comment by hhaAndroid** [comment]
@KyanChen Sorry, we have not tested the mps backend. Can you describe it in detail?

**Comment by xin-li-67** [comment]
Hi, please provide a detailed list of your local environment, including PyTorch, MMEngine, MMCV, etc. Thanks!
