### ISSUE TITLE
SyntaxError: There are syntax errors in config file /tmp/tmp43zsdqnj/tmpezj57n8l.py: invalid syntax (<unknown>, line 7)

### ISSUE THREAD

**Issue by dsbyprateekg** [open-mmlab/mmyolo#657]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

While trying to make an inference on a test image with rotated_rtmdet_l-coco_pretrain-3x-dota_ms-06d248a2.pth model as below-
![image](https://user-images.githubusercontent.com/30830541/224693473-756bb61a-ddf8-4fc8-90a8-77e296158354.png)

I got the following error in Kaggle -
![image](https://user-images.githubusercontent.com/30830541/224693641-f1edbd77-9bb3-4caf-9463-357e013b18ec.png)

My Kaggle notebook link is here to reproduce the issue-
[https://www.kaggle.com/code/iamprateek/mmdetection-rtmdet?scriptVersionId=121973329](url)

### Environment

Kaggle

**Comment by hhaAndroid** [comment]
@dsbyprateekg Thank you very much for your feedback! I see that you seem to be confusing mmyolo and mmrotate. if your weights and configuration are from mmrotate, i suggest you just use mmrotate. I'd like to know what your actual needs are.

**Comment by dsbyprateekg** [comment]
@hhaAndroid thanks for your response!
My actual use case is to detect an object on aerial images.
The image resolution is high and the object is in both size small and big.

I have tried YOLO now I want to do an experiment with RTMDet.
This is my first time using this repo, so please guide me correctly for my experiment.

**Comment by hhaAndroid** [comment]
@dsbyprateekg Thank you for using it. If you just want to use the rotation detection function you can use mmrotate, which is a rotation detection toolbox. mmyolo's rotation detection function still needs to be improved

**Comment by dsbyprateekg** [comment]
@hhaAndroid I checked the colab tutorial of MMRotate and I am able to train the custom dataset. Can you please tell e how can I interpret the result list from this line of code-
![image](https://user-images.githubusercontent.com/30830541/225804625-01a4a131-c39f-47ed-b948-0f923e581db1.png)

I want to store the coordinates, confidence score, and class name in a dataframe.

**Comment by hhaAndroid** [comment]
@dsbyprateekg Is this code inside mmrotate? If so, you can go to mmrotate and create the issue
