### ISSUE TITLE
export, yolox_tiny, model_only, self.backend

### ISSUE THREAD

**Issue by josh3255** [open-mmlab/mmyolo#660]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

when i run to below command

```shell
python projects/easydeploy/tools/export.py configs/yolox/yolox_nano_8xb8-300e_coco.py weights/yolox_tiny_8xb8-300e_coco_20220919_090908-0e40a6fc.pth --work-dir work_dirs/yolov7_export     --img-size 320 320     --batch 1     --device cpu     --simplify --opset 11 --model-only
```

error occured like this
```
Traceback (most recent call last):
  File "projects/easydeploy/tools/export.py", line 142, in <module>
    main()
  File "projects/easydeploy/tools/export.py", line 98, in main
    baseModel=baseModel, postprocess_cfg=postprocess_cfg)
  File "/mmyolo/projects/easydeploy/model/model.py", line 41, in __init__
    self.__switch_deploy()
  File "/mmyolo/projects/easydeploy/model/model.py", line 56, in __switch_deploy
    if self.backend in (1, 2, 3):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'DeployModel' object has no attribute 'backend'
```

### Environment

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.7.0
MMEngine: 0.6.0
MMCV: 2.0.0rc4
MMDetection: 3.0.0rc6
MMYOLO: 0.4.0+

**Comment by xin-li-67** [comment]
Hi, thanks for trying MMYolo and EasyDeploy. You missed the `backend` argument while exporting the model. As the [code](https://github.com/open-mmlab/mmyolo/blob/6341f0e31b079e9eacdd34cf9bcebccbd89475e3/projects/easydeploy/tools/export.py#L45) mentions, you have to specify the target backend. For ONNXRuntime, please use 1; for TensorRT8 and TensorRT7, please use 2 and 3, respectively.

**Comment by VJoer** [comment]
> Hi, thanks for trying MMYolo and EasyDeploy. You missed the `backend` argument while exporting the model. As the [code](https://github.com/open-mmlab/mmyolo/blob/6341f0e31b079e9eacdd34cf9bcebccbd89475e3/projects/easydeploy/tools/export.py#L45) mentions, you have to specify the target backend. For ONNXRuntime, please use 1; for TensorRT8 and TensorRT7, please use 2 and 3, respectively.

Hi, the default value of the `backend` is set to 1,  and the setting does not need to be display, the bug is caused by this line of [code](https://github.com/open-mmlab/mmyolo/blob/6341f0e31b079e9eacdd34cf9bcebccbd89475e3/projects/easydeploy/tools/export.py#L90),  backend is set in postprocess_cfg dict. Is there another way to get the onnxruntiem model without nms op
