### ISSUE TITLE
KeyError: 'YOLODetector is not in the model registry.

### ISSUE THREAD

**Issue by yaojiayan** [open-mmlab/mmyolo#661]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Hello, I used this document(https://mmyolo.readthedocs.io/zh_CN/latest/) to install mmyolo with the source code. There was an error when installing mmdet,please see below:
ERROR: Could not find a version that satisfies the requirement mmdet>=3.0.0rc6 (from mmyolo) (from versions: 0.6.0, 0.6.1, 0.6.2, 1.0rc2, 1.0rc3, 1.0rc4, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.15.1, 2.16.0, 2.17.0, 2.18.0, 2.18.1, 2.19.0, 2.19.1, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.24.1, 2.25.0, 2.25.1, 2.25.2, 2.25.3, 2.26.0, 2.27.0, 2.28.0, 2.28.1, 3.0.0rc0, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4, 3.0.0rc5)
ERROR: No matching distribution found for mmdet>=3.0.0rc6
And I installed 3.0.0rc5.But I also have an installation error and I install 0.3.2
ERROR: Could not find a version that satisfies the requirement mmengine>=0.6.0 (from versions: 0.0.1rc0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2)
ERROR: No matching distribution found for mmengine>=0.6.0

However, I was not able to run the document source case to verify that the installation was successful, and it reported the following error:
KeyError: 'YOLODetector is not in the model registry. Please check whether the value of `YOLODetector` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/tutorials/config.html#import-custom-python-modules'

In the  document,I use this codes：python demo/image_demo.py demo/demo.jpg \
                          yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py \
                          yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth

### Environment

pytorch 1.11.0
cuda 11.3

**Comment by yaojiayan** [comment]
I'm sorry, I've already solved the problem. Because I didn't have this problem when I switched to the RTX3090. I first rented titan xp and installed it on it. But why is that

**Comment by yaojiayan** [comment]
（自动回复）机电院团学学术部已经收到

**Comment by clw5180** [comment]
配置文件中需要增加 default_scope = 'mmyolo' ，有用掌声

**Comment by yaojiayan** [comment]
（自动回复）机电院团学学术部已经收到

**Comment by Missfoxsy** [comment]
> 配置文件中需要增加 default_scope = 'mmyolo' ，有用掌声

请问是哪个配置文件呢
