### ISSUE TITLE
Question:  add plugin and evaluate model size problem.

### ISSUE THREAD

**Issue by yeelokchau** [open-mmlab/mmyolo#664]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Hi, dear developers. I have one question here.

1. When I change the backbone to Timm backbone and add plugins such as CBAM and ContextBlock, it does not work. So What libraries can support plugins, just mmyolo backbone? When I read the mmapi, I do not see the answer. Pls help me to answer it. If mmyolo can not do Timm backbone, can we do in the future?

![60ac9c7092ab0e0f5b9ca64dc5029ba](https://user-images.githubusercontent.com/26769029/225032236-4412bc68-9793-4970-b19a-95c792fa91ad.png)
---------------------------------------------------------------------------------------------------
error:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmcls/models/backbones/timm_backbone.py", line 84, in __init__
    self.timm_model = timm.create_model(
  File "/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/ghostnet.py", line 294, in ghostnet_100
    model = _create_ghostnet('ghostnet_100', width=1.0, pretrained=pretrained, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/ghostnet.py", line 278, in _create_ghostnet
    return build_model_with_cfg(
  File "/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/helpers.py", line 537, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/Swin-Transformer-Object-Detection/mmyolo/mmyolo/models/detectors/yolo_detector.py", line 41, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 30, in __init__
    self.backbone = MODELS.build(backbone)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/buil
回溯（最近一次调用）：
  文件 “/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py”，第 121 行，第 build_from_cfg 行
    obj = obj_cls（**args） # 类型：忽略
  文件“/root/miniconda3/lib/python3.8/site-packages/mmcls/models/backbones/timm_backbone.py”，第 84 行，__init__
    self.timm_model = timm.create_model（
  文件“/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/factory.py”，第 71 行，create_model
    模型 = create_fn（预训练=预训练，pretrained_cfg=pretrained_cfg，**kwargs）
  文件“/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/ghostnet.py”，第294行，ghostnet_100
    模型 = _create_ghostnet（'ghostnet_100'， 宽度=1.0， 预训练=预训练， **kwargs）
  文件“/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/ghostnet.py”，第278行，_create_ghostnet
    返回build_model_with_cfg（
  文件“/root/miniconda3/lib/python3.8/site-packages/timm-0.6.12-py3.8.egg/timm/models/helpers.py”，第 537 行，build_model_with_cfg
    model = model_cls（**kwargs） 如果model_cfg是 None else model_cls（cfg=model_cfg， **kwargs）
类型错误：__init__（） 有一个意外的关键字参数“插件”

在处理上述异常期间，发生了另一个异常：

回溯（最近一次调用）：
  文件 “/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py”，第 121 行，第 build_from_cfg 行
    obj = obj_cls（**args） # 类型：忽略
  文件“/root/Swin-Transformer-Object-Detection/mmyolo/mmyolo/models/detectors/yolo_detector.py”，第 41 行，第 __init__ 行
    超级（）.__init__（
  文件“/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py”，第 30 行，__init__
    self.backbone = MODELS.build（backbone）
  文件 “/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py“，第 548 行，在构建中
    return self.build_func（cfg， *args， **kwargs， registry=self）
  文件 “/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/buil

### Environment

Tutorial Env

**Comment by Nioolek** [comment]
The class `mmcls.TIMMBackbone` do not support keyword argument `plugins`.  If you want to add `plugins`, you can add some codes, and register it into mmyolo.

**Comment by nakuda1** [comment]
> The class `mmcls.TIMMBackbone` do not support keyword argument `plugins`. If you want to add `plugins`, you can add the backbone in mmyolo, then, add the plugins in codes, and register the backbone to mmyolo.

It seems like that mmclass, mmdetection  backbone in mmyolo also can not add plugins? is that right.
