### ISSUE TITLE
添加新的优化器Lion

### ISSUE THREAD

**Issue by WanShaw** [open-mmlab/mmyolo#665]
### What is the problem this feature will solve?

我想添加新的优化器Lion，请问如何实现

### What is the feature you are proposing to solve the problem?

None

### What alternatives have you considered?

None

**Comment by Nioolek** [comment]
`mmengine0.6.0` 版本已经支持了 `Lion` 优化器，使用方式你可以参考： https://github.com/open-mmlab/mmengine/pull/952。
如果您使用中遇到了问题，可以重新 open 这个 issue 。

**Comment by WanShaw** [comment]
太感谢了，谢谢
