### ISSUE TITLE
tools/analysis_tools/browse_dataset.py  visualize datasetsloader error

### ISSUE THREAD

**Issue by liuhaiyang2018** [open-mmlab/mmyolo#670]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

![image](https://user-images.githubusercontent.com/36877347/225676976-cb34e8ba-e99c-4cf9-9458-7ae8ba09e055.png)

### Environment

mmyolo v 0.5.0

**Comment by liuhaiyang2018** [comment]
![1678988435493](https://user-images.githubusercontent.com/36877347/225706698-25cc8b9b-28e8-4ef1-8f62-2fe25d810143.png)
I debugged the code and found that there was a problem with the scaling function in the data agu part of the test

**Comment by liuhaiyang2018** [comment]
![image](https://user-images.githubusercontent.com/36877347/225707097-e456f217-504b-40c2-9574-7669ec51355b.png)

**Comment by liuhaiyang2018** [comment]
dict(
        type='mmdet.FixShapeResize',
        width=img_scale[0],
        height=img_scale[1],
        keep_ratio=False,
        interpolation='bicubic'),
It has the same problem

mmdet==3.0.0rc6

**Comment by hhaAndroid** [comment]
@liuhaiyang2018 The dev branch has been fixed, please try it

**Comment by liuhaiyang2018** [comment]
@hhaAndroid  What's the problem?

**Comment by liuhaiyang2018** [comment]
![image](https://user-images.githubusercontent.com/36877347/225929440-ff96ba97-b70e-47df-9bf6-3f24c6e84c91.png)

**Comment by liuhaiyang2018** [comment]
![image](https://user-images.githubusercontent.com/36877347/225940662-c0f536eb-1694-448e-a16b-1a5d7788cac2.png)
![image](https://user-images.githubusercontent.com/36877347/225940984-db738f53-760e-4738-8204-967a2505958c.png)

**Comment by hhaAndroid** [comment]
@liuhaiyang2018 Are you running the dev branch?
