### ISSUE TITLE
error export onnx using easydeploy/tools/export.py

### ISSUE THREAD

**Issue by Handsome-cp** [open-mmlab/mmyolo#671]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

when export my rotated .pth to onnx, error occoured:

Traceback (most recent call last):
  File "./projects/easydeploy/tools/export.py", line 142, in <module>
    main()
  File "./projects/easydeploy/tools/export.py", line 104, in main
    deploy_model(fake_input)
  File "/project/chenpin/Anaconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/project/chenpin/mmyolo/projects/easydeploy/model/model.py", line 148, in forward
    return self.pred_by_feat(*neck_outputs)
  File "/project/chenpin/mmyolo/projects/easydeploy/model/model.py", line 125, in pred_by_feat
    bboxes = bbox_decoder(flatten_priors[None], flatten_bbox_preds,
  File "/project/chenpin/mmyolo/mmyolo/models/task_modules/coders/distance_angle_point_coder.py", line 61, in decode
    assert pred_bboxes.size(-1) == 5

I tried with rtmdet-r_s_fast_1xb8-36e_dota_20230224_110307-3946a5aa.pth downloaded in mmyolo, same problem occoured.

### Environment

sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.2
OpenCV: 4.7.0
MMEngine: 0.6.0
MMCV: 2.0.0rc4
MMDetection: 3.0.0rc6
MMYOLO: 0.5.0+dc85144

**Comment by hhaAndroid** [comment]
@triple-Mu

**Comment by Handsome-cp** [comment]
> Could you please show me your detail command?

python ./projects/easydeploy/tools/export.py \
	/project/***/mmyolo/works/rtmdet-r_s-dota-ms-1/rtmdet-r_s_fast_1xb8-36e_dota-ms-***.py \
	/project/***/mmyolo/works/rtmdet-r_s-dota-ms-1/epoch_1.pth \
	--work-dir /project/***/mmyolo/works/rtmdet-r_s-dota-ms-1 \
    --img-size 1024 1024 \
    --batch 1 \
    --device cpu \
    --simplify \
	--opset 11 \
	--backend 1 \
	--pre-topk 1000 \
	--keep-topk 100 \
	--iou-threshold 0.65 \
	--score-threshold 0.25

**Comment by Handsome-cp** [comment]
> Could you please show me your detail command?

python ./projects/easydeploy/tools/export.py \
	/project/admin/mmyolo/works/rtmdet-r_s-dota-ms-1/rtmdet-r_s_fast_1xb8-36e_dota-ms-1.py \
	/project/admin/mmyolo/works/rtmdet-r_s-dota-ms-1/epoch_1.pth \
	--work-dir /project/admin/mmyolo/works/rtmdet-r_s-dota-ms-1 \
    --img-size 1024 1024 \
    --batch 1 \
    --device cpu \
    --simplify \
	--opset 11 \
	--backend 1 \
	--pre-topk 1000 \
	--keep-topk 100 \
	--iou-threshold 0.65 \
	--score-threshold 0.25
