### ISSUE TITLE
Hope to add yolov5-pose

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmyolo#68]
### What is the problem this feature will solve?

I hope to add yolov5-pose

### What is the feature you are proposing to solve the problem?

I hope to add yolov5-pose, I feel that it should be possible to directly return to the key point performance

**Comment by hhaAndroid** [comment]
@Deep-learning999 This is a very nice feature that is planned. If you are interested, please create a PR or we cooperate to develop!

**Comment by Deep-learning999** [comment]
If you use yolov5_v6.2-pose, the effect should be good@hhaAndroid

**Comment by Bovey0809** [comment]
I'm trying to make it work in mmyolo, I've developed my own yolo-pose series based on yolox official code including yolov5-pose and yolox-pose, once finished the PR will be uploaded. Mark here for future discussion.
