### ISSUE TITLE
./projects/easydeploy/tools/export.py can not export onnx model

### ISSUE THREAD

**Issue by swo026** [open-mmlab/mmyolo#680]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

I want to export model by
```shell
python ./projects/easydeploy/tools/export.py E:\work\project\mmlab\mmyolo-main\configs\fire\yolov5_l-v61_syncbn_fast_8xb16-300e_fire.py E:\work\project\mmlab\mmyolo-main\work_dirs\yolov5_l-v61_syncbn_fast_8xb16-300e_fire\best_coco\bbox_mAP_epoch_100.pth --work-dir E:/work/project/mmlab/mmyolo-main/work_dirs/yolov5_l-v61_syncbn_fast_8xb16-300e_fire --img-size 640 640 --batch 1 --device cpu --opset 11 --backend 1 --pre-topk 1000 --keep-topk 100 --iou-threshold 0.65 --score-threshold 0.25
```

but only output 
```shell
Loads checkpoint by local backend from path: E:\work\project\mmlab\mmyolo-main\work_dirs\yolov5_l-v61_syncbn_fast_8xb16-300e_fire\best_coco\bbox_mAP_epoch_100.pth
03/21 16:42:24 - mmengine - ?[5m?[4m?[33mWARNING?[0m - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
03/21 16:42:24 - mmengine - ?[5m?[4m?[33mWARNING?[0m - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
```
no error throw, no model export

### Environment

sys.platform: win32
Python: 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.74
GCC: n/a
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_7
5,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimen
tal -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, US
E_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.7.0
MMEngine: 0.7.0
MMCV: 2.0.0rc4
MMDetection: 3.0.0rc6
MMYOLO: 0.5.0+

**Comment by hhaAndroid** [comment]
@triple-Mu
