### ISSUE TITLE
Different results with mmyolo exported models

### ISSUE THREAD

**Issue by LidiaFantauzzo** [open-mmlab/mmyolo#683]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Hi everyone,

I used the yolov8 model from mmyolo to train a model with my customized dataset in python (config file in "additional information").  
Then I exported the model both with TensorRT and ONNX to be used on a c++ application, but when I compared the results obtained with all of them (original in pyhton, tensorrt and onnx in c++), I noticed a lot of differences.
The score threshold used for all the inferences was 0.01. 

So, I tested the trained model with Python using the script 
`python mmyolo-0.5.0/demo/image_demo.py /software/OpenMMLab/data/images/1234.bmp mmyolo-0.5.0/configs/custom_dataset/yolov8_test.py mmdeploy-1.0.0rc3/models/Yolo/latest.pth --out-dir output --device cuda:0 --score-thr 0.01`

Here, the command used to export the model are reported
TENSORRT
`python ./tools/deploy.py ../mmyolo-0.5.0/configs/deploy/detection_tensorrt-fp16_dynamic-64x64-1344x1344.py ../mmyolo-0.5.0/configs/custom_dataset/yolov8.py ./models/Yolo/latest.pth ./models/Yolo/test_yolo.bmp --work-dir ./deployed/YOLO/TRT --device cuda:0 --dump-info`

ONNX
`python ./tools/deploy.py ../mmyolo-0.5.0/configs/deploy/detection_onnxruntime_dynamic.py ../mmyolo-0.5.0/configs/custom_dataset/yolov8.py ./models/Yolo/latest.pth ./models/Yolo/test_yolo.bmp --work-dir ./deployed/YOLO/ONNX --device cuda:0 --dump-info`

At this point I used the c++ API mmdeploy-1.0.0rc3/demo/csrc/cpp/detector.cxx to test the exported models and these are some of the results obtained, compared:
respectively original model - exported TRT model - exported ONNX model

![Immagine 2023-03-21 165442](https://user-images.githubusercontent.com/65127026/226666126-34005277-a4c2-4c10-8a4a-6e1be45604ee.jpg)

![Immagine 2023-03-21 165542](https://user-images.githubusercontent.com/65127026/226666177-ee06ee64-c974-4554-bb83-bb51cc0b48d6.jpg)

Can you help me find out why there are so many differences between original and exported models?
Thank you so much

### Environment

Output of `python mmyolo/utils/collect_env.py`

sys.platform: linux
Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070 SUPER
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1
OpenCV: 4.7.0
MMEngine: 0.7.0
MMCV: 2.0.0rc4
MMDetection: 3.0.0rc6
MMYOLO: 0.5.0+

MMDEPLOY VERSION 1.0.0

### Additional information

YOLOV8 CONFIG FILE 

_base_ = '../yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py'
max_epochs = 200  
data_root = '/home/PycharmProjects/OpenMMYolo/mmyolo/data/unified/'  
work_dir = './work_dirs/yolov8'

load_from = '/home/PycharmProjects/OpenMMYolo/mmyolo/yolov8_s_syncbn_fast_8xb16-500e_coco_20230117_180101-5aa5f0f1.pth' 
train_batch_size_per_gpu = 16
train_num_workers = 16  
save_epoch_intervals = 20  
base_lr = 0.01
class_name = ('Gap', 'Squat', 'Wheelslip', 'LightSquat', 'AggregatedSquat', 'Weld', 'SideSquat', 'Corrugation', 'HeadChecking')
num_classes = len(class_name)
metainfo = dict(
    classes=class_name,
    palette=[(220, 20, 60), (191, 157, 216), (230, 250, 100), (160, 250, 100), (100, 250, 220), (31, 112, 233), (200, 81, 94), (233, 92, 224), (255, 32, 0)])
train_cfg = dict(
    max_epochs=max_epochs,
    val_begin=20,  
    val_interval=save_epoch_intervals  )
model = dict(
    bbox_head=dict(
        head_module=dict(num_classes=num_classes)),
    train_cfg=dict(
        initial_assigner=dict(num_classes=num_classes),
        assigner=dict(num_classes=num_classes)))
train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    dataset=dict(
        type=_base_.dataset_type,
        data_root=data_root,
        metainfo=metainfo,
        ann_file='annotations/trainval.json',
        data_prefix=dict(img='images/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        pipeline=_base_.train_pipeline))
val_dataloader = dict(
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file='annotations/test.json',
        data_prefix=dict(img='images/')))
test_dataloader = val_dataloader
val_evaluator = dict(ann_file=data_root + 'annotations/test.json')
test_evaluator = val_evaluator
optim_wrapper = dict(optimizer=dict(lr=base_lr))
default_hooks = dict(
    checkpoint=dict(
        type='CheckpointHook',
        interval=save_epoch_intervals,
        max_keep_ckpts=5,
        save_best='auto'),
    param_scheduler=dict(max_epochs=max_epochs),
    # logger output interval
    logger=dict(type='LoggerHook', interval=10))
visualizer = dict(vis_backends=[dict(type='LocalVisBackend'), dict(type='WandbVisBackend')])

**Comment by LidiaFantauzzo** [comment]
Update the issue with the .pth file obtained by training the yolov8 model and then used to export the model:
[yolov8_model.pth](https://drive.google.com/file/d/1REH7wOBRP-G9mI3TXcgZflVDe9jROxU1/view?usp=sharing)

**Comment by hhaAndroid** [comment]
@LidiaFantauzzo Thank you for your attention, the deployment issue needs to be created in mmdeploy repo.

**Comment by LidiaFantauzzo** [comment]
@hhaAndroid Ok, thank you so much, I will repost it there!
