### ISSUE TITLE
Does mmyolo support pytorch 2.0?

### ISSUE THREAD

**Issue by kelvinwang139** [open-mmlab/mmyolo#687]
### What is the problem this feature will solve?

support pytorch 2.0

pytorch 2.0 is official released. Does mmyolo support pytorch 2.0 (officially announced by pytorch that 2.0 is 100% backward compatible by definition.)

### What is the feature you are proposing to solve the problem?

support pytorch 2.0

**Comment by Nioolek** [comment]
Thank you for your attention to mmyolo.
Mmyolo can be used without modifying any code in pytorch2.0.
You may meet error while using `compile` mode, and we will support `compile` mode in future release.
