### ISSUE TITLE
For small and occluded objects

### ISSUE THREAD

**Issue by noreenanwar** [open-mmlab/mmyolo#69]
Hi, thank you for your amazing work.I just want to ask that this algo can able to detect small or occluded objects(just one class)? if not then can we add self attention mechanism in this algo?.

**Comment by hhaAndroid** [comment]
@noreenanwar For dense object detection you can try mmdet's [crowddet](https://github.com/open-mmlab/mmdetection/pull/8744).

**Comment by noreenanwar** [comment]
The think is that I want to use detected object attention maps as I am just interested for detected instance

**Comment by matrixgame2018** [comment]
I think you can try  `demo/featmap_vis_demo.py`  which provides cam map about the detection object.

**Comment by matrixgame2018** [comment]
> The thing is that I want to use detected object attention maps as I am just interested for detected instance

I think you can try demo/featmap_vis_demo.py which provides cam map about the detection object.

**Comment by noreenanwar** [comment]
i tried this but i want to utilisé detected information for further process that’s why i need self attention thing from where i can use response map correctly. because my goal is to fuse two images information to get one.

**Comment by cydiachen** [comment]
> i tried this but i want to utilisé detected information for further process that’s why i need self attention thing from where i can use response map correctly. because my goal is to fuse two images information to get one.

To the best of my knowledge, you can try the following approaches to boost the performance of existing detectors. 
1. Strong backbone;
2. Modify the FPN in the network to ensure extreme small objects can be detected.
3. Stronger data augmentation method (e,g. grid mask and so on).

You can also alter the network structures to add attention mechanisms.
