### ISSUE TITLE
Followed the instructions but got error: module 'torch' has no attribute 'asarray'

### ISSUE THREAD

**Issue by wangbin-ouhin** [open-mmlab/mmyolo#696]
### 📚 The doc issue

Hi there,

# Doc URL: https://mmyolo.readthedocs.io/en/latest/get_started/15_minutes_object_detection.html

An error occurred when use end2end.onnx model to perform a basic image inference as bellow, .
```
python projects/easydeploy/tools/image-demo.py \
    data/cat/images/IMG_20210728_205312.jpg \
    configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
    work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/end2end.onnx \
    --device cpu
```
# Error

>   File "projects/easydeploy/tools/image-demo.py", line 152, in <module>
>     main()
>   File "projects/easydeploy/tools/image-demo.py", line 100, in main
>     pad_param = torch.asarray(
> AttributeError: module 'torch' has no attribute 'asarray'

# Torch was installed correctly. Here is the conda list result.
```
>conda list | findstr pytorch
pytorch                   1.10.2          py3.8_cuda10.2_cudnn7_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                0.10.2               py38_cu102    pytorch
torchvision               0.11.3               py38_cu102    pytorch
```

# This error occurred in python too.
```
Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.tensor([1, 2, 3])
>>> b = torch.asarray(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'asarray'
```

After checked the instructions again and again, got no clue, is there anything wrong in my conda environment?
Waiting for your reply.

Best regards,

**Comment by hhaAndroid** [comment]
@triple-Mu

**Comment by triple-Mu** [comment]
Sorry. It may be caused by lower pytorch.
You can try torch.from_numpy replease torch.asarray.
I will fix it soon.

**Comment by wangbin-ouhin** [comment]
Thank you for your reply. 
After change the code as bellow. It worked.

# Line:100-102
```
        pad_param = torch.asarray(
            [pad_param[2], pad_param[0], pad_param[2], pad_param[0]],
            device=args.device)
```
↓↓↓↓↓↓↓↓↓↓↓
`        pad_param = torch.from_numpy(np.array([pad_param[2], pad_param[0], pad_param[2], pad_param[0]]))
`
# Line:104
```
        scale_factor = torch.asarray(scale_factor * 2, device=args.device)
```
↓↓↓↓↓↓↓↓↓↓↓
`        scale_factor = torch.from_numpy(np.array([scale_factor * 2]))
`

**Comment by triple-Mu** [comment]
Great!

**Comment by FIFCOM** [comment]
> Thank you for your reply. After change the code as bellow. It worked.
> 
> # Line:100-102
> ```
>         pad_param = torch.asarray(
>             [pad_param[2], pad_param[0], pad_param[2], pad_param[0]],
>             device=args.device)
> ```
> 
> ↓↓↓↓↓↓↓↓↓↓↓ ` pad_param = torch.from_numpy(np.array([pad_param[2], pad_param[0], pad_param[2], pad_param[0]]))`
> 
> # Line:104
> ```
>         scale_factor = torch.asarray(scale_factor * 2, device=args.device)
> ```
> 
> ↓↓↓↓↓↓↓↓↓↓↓ ` scale_factor = torch.from_numpy(np.array([scale_factor * 2]))`

Running `image-demo.py` with `cuda:0` after the modification results in:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

This is because pad_param and scale_factor are not on the gpu and need to be moved to it, just add them under pad_param and scale_factor:
```python
pad_param = torch.from_numpy(np.array([pad_param[2], pad_param[0], pad_param[2], pad_param[0]]))
pad_param = pad_param.to(args.device) # move pad_param to the same device


scale_factor = torch.from_numpy(np.array([scale_factor * 2]))
scale_factor = scale_factor.to(args.device) #  move scale_factor to the same device
```

---

修改后使用`cuda:0`运行`image-demo.py`会出现：
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

这是因为pad_param和scale_factor不在显卡上，需要将其移到到显卡上，只需在pad_param和scale_factor下添加：
```
pad_param = torch.from_numpy(np.array([pad_param[2], pad_param[0], pad_param[2], pad_param[0]]))
pad_param = pad_param.to(args.device)  # 将 pad_param 移动到相同的设备


scale_factor = torch.from_numpy(np.array([scale_factor * 2]))
scale_factor = scale_factor.to(args.device) # 将 scale_factor 移动到相同的设备
```
