### ISSUE TITLE
About yolox_head ‘batch_gt_instances_ignore’

### ISSUE THREAD

**Issue by paihuai0** [open-mmlab/mmyolo#70]
### What is the problem this feature will solve?

when I read yolox_head code I found parameter “batch_gt_instances_ignore”，but it is set to None,I haven't found how to use it in the code，I can get more of it？

### What is the feature you are proposing to solve the problem?

about “batch_gt_instances_ignore”

**Comment by hhaAndroid** [comment]
@paihuai0 yolox head doesn't actually use this data, it just doesn't delete it.
