### ISSUE TITLE
安装时出现错误

### ISSUE THREAD

**Issue by PhenixFeather** [open-mmlab/mmyolo#715]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

按照说明文档安装mmyolo，进行到步骤mim install -v -e时出现如下错误：

ERROR: -f is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

确定已经在mmyolo的目录之下，且前面的步骤都正确执行。

### Environment

Traceback (most recent call last):
  File "./utils/collect_env.py", line 7, in <module>
    import mmyolo
ModuleNotFoundError: No module named 'mmyolo'

**Comment by Nioolek** [comment]
The correct command is `mim install -v -e .` ,  did you ignore the ` . ` at the end ?

**Comment by PhenixFeather** [comment]
Indeed, thx.
