### ISSUE TITLE
Fail to train yolov8_s_mask-refine with input size (320,240)

### ISSUE THREAD

**Issue by zero0kiriyu** [open-mmlab/mmyolo#716]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

![image](https://user-images.githubusercontent.com/30134805/229590151-ec675626-9bf1-4675-b52c-96f4f5734f19.png)

I am trying to modify the input size of Yolov8_s_mask-refine to 320x240, but using this input size causes an error in the Albu data augmentation. After checking, I found that it might be a problem with the mask-to-bbox conversion process or that mask was incorrectly modified during one of the data augmentation steps, causing the error bbox shown in the figure below.
![image](https://user-images.githubusercontent.com/30134805/229588050-cb206ad4-8ac9-41a7-9169-0340eaf69fc5.png)
This is my train_pipeline, only the image_scale is changed.
![image](https://user-images.githubusercontent.com/30134805/229588416-96172de7-064e-4a19-acc9-48667357d467.png)

### Environment

mmyolo dev branch

**Comment by Nioolek** [comment]
Hello, while the input img is not 1:1 scale, the `YOLOv5RandomAffine`  may occur error. We are fixing this bug, you can copy the  `YOLOv5RandomAffine` code from 
`https://github.com/open-mmlab/mmyolo/blob/4202b8e4e2c8ec3f879227e93531f87ba5a7a5f9/mmyolo/datasets/transforms/transforms.py`
