### ISSUE TITLE
training without  pretrained 

### ISSUE THREAD

**Issue by baowenshuwh** [open-mmlab/mmyolo#728]
### Model/Dataset description

I want to use RTMDet to train my own data set without using pre-training weights. What should I do?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by hhaAndroid** [comment]
`model=dict(backbone=dict(init_cfg=None))`

**Comment by baowenshuwh** [comment]
Ok, thank you for your reply

**Comment by Tuerte** [comment]
Hi，I want to usr pretrained model to train my datasets. how to set config file. I have set the dict(init_cfg="pretrained", checkpoint='pth_file'), but occured some issues, like this : 
04/18 09:31:29 - mmengine - INFO - load model from: weights/yolov8_s_syncbn_fast_8xb16-500e_coco_20230117_180101-5aa5f0f1.pth
04/18 09:31:29 - mmengine - INFO - Loads checkpoint by local backend from path: /weights/yolov8_s_syncbn_fast_8xb16-500e_coco_20230117_180101-5aa5f0f1.pth
04/18 09:31:29 - mmengine - WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: xxxxxxxx
missing keys in source state_dict: xxxxxxx
