### ISSUE TITLE
运行15分钟上手mmyolo目标检测示例报错

### ISSUE THREAD

**Issue by ChenWanger** [open-mmlab/mmyolo#746]
### 📚 The doc issue

RuntimeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `YOLOv5CocoDataset` in mmyolo/datasets/yolov5_coco.py: class `Albu` in mmdet/datasets/transforms/transforms.py: albumentations is not installed
不知出了什么问题，求教该如何解决

**Comment by RangeKing** [comment]
@ChenWanger Pls follow the instruction to install MMYOLO.
https://github.com/open-mmlab/mmyolo/blob/dc85144fab20a970341550794857a2f2f9b11564/docs/en/get_started/installation.md?plain=1#L26
