### ISSUE TITLE
Accuracy after fine-tuning is much lower than ultralytics

### ISSUE THREAD

**Issue by zhouchuangchuang** [open-mmlab/mmyolo#769]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

First of all, thanks a lot for your contribution! The framework of MMDet is excellent!

Now I have met a weird problem. I tried to retrain YOLOv5m on the same dataset I collected with MMYOLO and Ultralytics, separately. 
In MMYOLO, I used the method proposed in `15_minutes_object_detection.md'.
In Ultralytics, I used `yolo train models=yolov5m.pt xxxxxx`

It seems that the prediction accuracy after training is totally different, the accuracy in MMYOLO is about 0.5, but the value in Ultralytics is 0.8. (Using Faster RCNN, we can get about 0.75). How can the final results be such a difference with the same input size and same data augmentation methods?

### Environment

The same environments are installed based on the recommendations.

**Comment by zhouchuangchuang** [comment]
Sorry, I made an error in the dataset preprocessing step.

**Comment by TheRochVoices** [comment]
Hi @zhouchuangchuang , Can you tell what was the issue? I am currently facing the same issue where training yolov5 using ultralytiics gives aeound 0.8mAP, but mmyolo is giving around 0.5.
