### ISSUE TITLE
Hi, any doc/hands_on tutors to run the instance segmentaion part?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmyolo#82]
### 📚 The doc issue

Hi, any doc/hands on tutors to run the instance segmentaion part?

### Suggest a potential alternative/fix

Didn't see any code/doc about instance segmentation part.

**Comment by PeterH0323** [comment]
Will support it in the future. Thx for your attention. 😄

**Comment by jinfagang** [comment]
@hhaAndroid Hey, why you thumb down my issue? The instance segmenation is on your post, but not release the code? I didn't find any clue on where does it related with this repo....

**Comment by hhaAndroid** [comment]
@jinfagang  Sorry, it's my fault. I triggered it by mistake. We really haven't released the example split code yet, and we very sincerely accept your criticism. Thank you very much for your feedback!
