### ISSUE TITLE
训练自己的数据集时更换主干网络报错

### ISSUE THREAD

**Issue by MysteryNull** [open-mmlab/mmyolo#864]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

 File "E:\miniconda\envs\mmyolo\lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 239, in results2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

### Environment

_base_ = '../yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py'

custom_imports = dict(imports=['mmcls.models'],allow_failed_imports=False)
checkpoint_file = 'https://download.openmmlab.com/mmclassification/v0/mobilenet_v3/convert/mobilenet_v3_small-8427ecf0.pth'
max_epochs = 100
data_root = './data/mushroom/'
# data_root = '/root/workspace/mmyolo/data/cat/'  # Docker

work_dir = './work_dirs/mobilenet/yolov5_s-v61_syncbn_fast_1xb32-100e_mushroom'

# load_from = 'https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth'  # noqa

train_batch_size_per_gpu = 32
train_num_workers = 4

save_epoch_intervals = 2

# base_lr_default * (your_bs / default_bs)
base_lr = _base_.base_lr / 4

anchors = [
    [(68, 69), (154, 91), (143, 162)],  # P3/8
    [(242, 160), (189, 287), (391, 207)],  # P4/16
    [(353, 337), (539, 341), (443, 432)]  # P5/32
]

class_name = ('mushroomCap', )
num_classes = len(class_name)
metainfo = dict(classes=class_name, palette=[(220, 20, 60)])

train_cfg = dict(
    max_epochs=max_epochs, val_begin=20, val_interval=save_epoch_intervals)

deepen_factor = _base_.deepen_factor
widen_factor = 1.0
channels = [24,48,96]

model = dict(
    backbone=dict(
               _delete_=True,
	type='mmcls.MobileNetV3',
	arch='small',
	out_indices=(3,8,11),
	init_cfg=dict(
	      type='Pretrained',
	      checkpoint=checkpoint_file,
	      prefix='backbone.')),
    neck=dict(
	type='YOLOv5PAFPN',
	deepen_factor=deepen_factor,
	widen_factor=widen_factor,
	in_channels=channels,
	out_channels=channels),
    bbox_head=dict(
	type='YOLOv5Head',
	head_module=dict(
	       type='YOLOv5HeadModule',
	       in_channels=channels,
	       widen_factor=widen_factor)))

train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    dataset=dict(
        _delete_=True,
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=_base_.dataset_type,
            data_root=data_root,
            metainfo=metainfo,
            ann_file='annotations/trainval.json',
            data_prefix=dict(img='images/'),
            filter_cfg=dict(filter_empty_gt=False, min_size=32),
            pipeline=_base_.train_pipeline)))

val_dataloader = dict(
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file='annotations/trainval.json',
        data_prefix=dict(img='images/')))

test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'annotations/trainval.json')
test_evaluator = val_evaluator

optim_wrapper = dict(optimizer=dict(lr=base_lr))

default_hooks = dict(
    checkpoint=dict(
        type='CheckpointHook',
        interval=save_epoch_intervals,
        max_keep_ckpts=5,
        save_best='auto'),
    param_scheduler=dict(max_epochs=max_epochs),
    logger=dict(type='LoggerHook', interval=10))

**Comment by RangeKing** [comment]
@MysteryNull 可以参考[常见错误排除步骤](https://mmyolo.readthedocs.io/zh_CN/dev/recommended_topics/troubleshooting_steps.html#indexerror-list-index-out-of-range)解决

**Comment by MysteryNull** [comment]
感谢解答
