### ISSUE TITLE
I tried to implement the ablationcam of a Tood model using boxam vis demo.py, but it reports bugs.

### ISSUE THREAD

**Issue by Sudae827** [open-mmlab/mmyolo#878]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

I run the following command:
!python mmyolo/demo/boxam_vis_demo.py   mmdetectionv3.1.0/demo/2.jpg \
                                        mmdetectionv3.1.0/work_dirs/Swin/Swin-TOOD.py \
                                        mmdetectionv3.1.0/work_dirs/Swin/latest.pth  \
                                        --method ablationcam \
                                        --norm-in-bbox
And it reports:
Traceback (most recent call last):
  File "mmyolo/demo/boxam_vis_demo.py", line 152, in init_detector_and_visualizer
    eval(f'model_wrapper.detector.{target_layer}'))
  File "<string>", line 1, in <module>
  File "c:\Users\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Sequential' object has no attribute 'out_layers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmyolo/demo/boxam_vis_demo.py", line 276, in <module>
    main()
  File "mmyolo/demo/boxam_vis_demo.py", line 199, in main
    model_wrapper, boxam_detector_visualizer = init_detector_and_visualizer(
  File "mmyolo/demo/boxam_vis_demo.py", line 155, in init_detector_and_visualizer
    raise RuntimeError('layer does not exist', e)
RuntimeError: ('layer does not exist', AttributeError("'Sequential' object has no attribute 'out_layers'"))

Is heat map visualization not fully integrated with models in mmdetection yet? Should we contemplate incorporating heat map visualization into mmdet?

### Environment

sys.platform: win32
Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070 SUPER
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.55
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32535 版
GCC: n/a
PyTorch: 1.13.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.0
OpenCV: 4.8.0
MMEngine: 0.8.2
MMCV: 2.0.1
MMDetection: 3.1.0
MMYOLO: 0.6.0+

### Additional information

I used a tood config.py from mmdetection3.1.  The featmap_vis_demo.py worked well, but the boxam_vis_demo.py failed to generate heatmap.

**Comment by Sudae827** [comment]
Solved it

**Comment by zhanghay** [comment]
How?

**Comment by LeoWang95** [comment]
> 解决了

how to solve？
