### ISSUE TITLE
In the example in the tutorial, there was an error converting the detection cat ONNX model to engine

### ISSUE THREAD

**Issue by happylinhxl** [open-mmlab/mmyolo#889]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

In the example in the tutorial “15 minutes to get started with MMYOLO object detection” ，I tried to follow the tutorial once everything went smoothly ahead . However, an error occurred when converting the onnx model into an engine. Why? Did I miss any steps ？

The error is as follows : 

python projects/easydeploy/tools/build_engine.py ./work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/best_coco_bbox_mAP_epoch_40.onnx --device cuda:0 --img-size 640 640
[09/21/2023-13:49:00] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[09/21/2023-13:49:06] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/21/2023-13:49:06] [TRT] [W] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[09/21/2023-13:49:06] [TRT] [E] If_521_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape. Shapes are [1,-1] and [1,-1,1].
[09/21/2023-13:49:06] [TRT] [E] ModelImporter.cpp:771: While parsing node number 521 [If -> "scores"]:
[09/21/2023-13:49:06] [TRT] [E] ModelImporter.cpp:772: --- Begin node ---
[09/21/2023-13:49:06] [TRT] [E] ModelImporter.cpp:773: input: "onnx::If_1149"
output: "scores"
name: "If_521"
op_type: "If"
attribute {
  name: "then_branch"
  g {
    node {
      input: "onnx::Shape_1144"
      output: "1151"
      name: "Squeeze_522"
      op_type: "Squeeze"
      attribute {
        name: "axes"
        ints: -1
        type: INTS
      }
    }
    name: "torch-jit-export1"
    output {
      name: "1151"
      type {
        tensor_type {
          elem_type: 1
          shape {
            dim {
              dim_param: "ReduceSumnum_dets_dim_0"
            }
            dim {
              dim_param: "Splitboxes_dim_1"
            }
          }
        }
      }
    }
  }
  type: GRAPH
}
attribute {
  name: "else_branch"
  g {
    node {
      input: "onnx::Shape_1144"
      output: "1152"
      name: "Identity_523"
      op_type: "Identity"
    }
    name: "torch-jit-export2"
    output {
      name: "1152"
      type {
        tensor_type {
          elem_type: 1
          shape {
            dim {
              dim_param: "ReduceSumnum_dets_dim_0"
            }
            dim {
              dim_param: "Splitboxes_dim_1"
            }
            dim {
              dim_param: "Identity1152_dim_2"
            }
          }
        }
      }
    }
  }
  type: GRAPH
}

[09/21/2023-13:49:06] [TRT] [E] ModelImporter.cpp:774: --- End node ---
[09/21/2023-13:49:06] [TRT] [E] ModelImporter.cpp:777: ERROR: ModelImporter.cpp:195 In function parseGraph:
[6] Invalid Node - If_521
If_521_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape. Shapes are [1,-1] and [1,-1,1].
Traceback (most recent call last):
  File "projects/easydeploy/tools/build_engine.py", line 136, in <module>
    main(args)
  File "projects/easydeploy/tools/build_engine.py", line 131, in main
    builder.build(scales, fp16=args.fp16)
  File "projects/easydeploy/tools/build_engine.py", line 96, in build
    self.__build_engine(scale, fp16, with_profiling)
  File "projects/easydeploy/tools/build_engine.py", line 50, in __build_engine
    raise RuntimeError(

### Environment

2023/09/21 09:33:11 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 998610245
    GPU 0,1,2,3: NVIDIA GeForce RTX 4080
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 12.0, V12.0.76
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.11.0+cu113
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.12.0+cu113
    OpenCV: 4.8.0
    MMEngine: 0.8.4

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 998610245
    Distributed launcher: none
    Distributed training: False
    GPU number: 1

**Comment by xiebinghua** [comment]
I meet this problem， how to solve it？
