### ISSUE TITLE
Why yolox-s in mmyolo can be 40.8%(mAP)? However, official mAP of yolox-s is 40.5%?What you have modified?

### ISSUE THREAD

**Issue by lixiangMindSpore** [open-mmlab/mmyolo#89]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

Why yolox-s in mmyolo can be 40.8%(mAP)? However, official mAP of yolox-s is 40.5%?What you have modified?

### Environment

nothing special

**Comment by hhaAndroid** [comment]
@lixiangMindSpore It mainly includes 2 aspects:
1. Using multi_label, the performance can be about 0.2
2. Algorithms fluctuate

**Comment by lixiangMindSpore** [comment]
> @lixiangMindSpore It mainly includes 2 aspects:
> 
> 1. Using multi_label, the performance can be about 0.2
> 2. Algorithms fluctuate

How to use multi_label?

**Comment by RangeKing** [comment]
@lixiangMindSpore 
Please refer to this line in the config file:

https://github.com/open-mmlab/mmyolo/blob/main/configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py#L93

**Comment by lixiangMindSpore** [comment]
> @lixiangMindSpore Please refer to this line in the config file:
> 
> https://github.com/open-mmlab/mmyolo/blob/main/configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py#L93

Official YOLOX don't possess it. How to modify it in Official YOLOX?

**Comment by RangeKing** [comment]
@lixiangMindSpore 
In MMYOLO, it's the same setting.
https://github.com/open-mmlab/mmyolo/blob/main/configs/yolox/yolox_s_8xb8-300e_coco.py#L97

If you want to modify official YOLOX, you can go to the official YOLOX repo and open a new issue about it.
