### ISSUE TITLE
How to start with custom datasets?

### ISSUE THREAD

**Issue by xingyueye** [open-mmlab/mmyolo#92]
### What is the problem this feature will solve?

Hi~ I found that 'CustomDataset.py' used in original 'mmDet' is deprecated, as well as some optional parameters like 'classes'. Would you pls release a tutorial about how to train a yolov5 model with a custom dataset that possess different classes from coco.

### What is the feature you are proposing to solve the problem?

Train YOLO model with custom datasets.

**Comment by RangeKing** [comment]
Hi @xingyueye , you could refer to this tutorial.
https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/user_guides/yolov5_tutorial.md
