### ISSUE TITLE
Whats the speed of other YOLOs you tested on NVIDIA 3090,  and how about the speed of RTMDet on T4 / V100 ?

### ISSUE THREAD

**Issue by floveqq** [open-mmlab/mmyolo#93]
### What is the problem this feature will solve?

Surprised to see the latest detector RTMDet, nice work.
But whats the speed of other yolos you tested on NVIDIA 3090, and how about the speed of RTMDet on T4 / V100 ?
You got other yolos' speed by testing mmyolo or their original repos ？
Thanks.

### What is the feature you are proposing to solve the problem?

I want to know the speed of other yolos on NVIDIA 3090, and the speed of rtmdet on T4 / V100

**Comment by RangeKing** [comment]
Hi @floveqq Thank you for your attention to MMYOLO and RTMDet.
RTMDet in MMYOLO is under development for now but already available in MMDetection. You can open a issue in MMDetection's repo.
And we will also update the benchmark about different YOLO algorithms later in MMYOLO.
