### ISSUE TITLE
REQUEST: Refine zh_cn/algorithm_descriptions/yolov5_description.md

### ISSUE THREAD

**Issue by xin-li-67** [open-mmlab/mmyolo#94]
### 📚 The doc issue

Hi~

Lately, I have been working on the translation on the algorithm_descriptions/yolov5_description.md, however, I noticed that there are some small places in the Chinese version might need some refinement or modification. I considered revising them by myself, but of course, this will not be the same as what the original developers originally wanted to express.

**Comment by PeterH0323** [comment]
Hi @xin-li-67 

You can open a PR and we will review and discuss together.

We are looking forward to it !

**Comment by hhaAndroid** [comment]
@xin-li-67 Are you interested in optimizing MMYOLO?

**Comment by xin-li-67** [comment]
> 

Sure, I would try my best on this.

**Comment by xin-li-67** [comment]
> @xin-li-67 Are you interested in optimizing MMYOLO?

I would love to. Just need more time to get more familiar with openmmlab code structure~

**Comment by hhaAndroid** [comment]
> 

You can join the mmyolo wechat group, we can give you more help.
