### ISSUE TITLE
Any plan for 'yolov8 instance segmentation'?

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmyolo#947]
### What is the problem this feature will solve?

YOLOv8 Detect, Segment and Pose models pretrained on the COCO dataset are available in [ultralytics](https://github.com/ultralytics/ultralytics). I'm a big fan of mmlab series and get familiar with mmdet and mmpose. Did mmyolo have a similar function in Segment and Pose, so that I can use mmyolo without mmdet/mmpose? I saw the yolo-v5-ins, what else?

![img](https://raw.githubusercontent.com/ultralytics/assets/main/im/banner-tasks.png)

### What is the feature you are proposing to solve the problem?

Add more features.

**Comment by nik123** [comment]
According to the #136 instance segmentation was in plans. However, it seems  that feature is not active development.

**Comment by chenxinfeng4** [comment]
I see, the feature is on developing. I'll swith to the ultralytics.
