### ISSUE TITLE
where is easydeploy?

### ISSUE THREAD

**Issue by aooxin** [open-mmlab/mmyolo#948]
### 📚 The doc issue

https://mmdeploy.readthedocs.io/zh-cn/latest/get_started.html
这个页面说有easydeploy，但是并没有发现对应的库，想问问这个库在哪里？

另外，我在使用mmdeploy转换tensorrt的时候，遇到了的问题。
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
12/14 17:15:38 - mmengine - ERROR - D:\anaconda\envs\mmdeploy\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

### Suggest a potential alternative/fix

完善mmyolo的deploy部分的文档和功能，在mmdeploy中没有单独支持mmyolo。

**Comment by aooxin** [comment]
@hhaAndroid

**Comment by Vjinqu** [comment]
@aooxin ，您好，我在使用mmdeploy转换tensorrt的时候遇到了和您一样的问题，请问您是如何解决的。

**Comment by Vjinqu** [comment]
> @aooxin ，您好，我在使用mmdeploy转换tensorrt的时候遇到了和您一样的问题，请问您是如何解决的。

sloved my problem 。use configs in [mmyolo](https://github.com/open-mmlab/mmyolo/tree/main/configs/deploy) to do the conversion
