### ISSUE TITLE
如何推理一张图片

### ISSUE THREAD

**Issue by todesti2** [open-mmlab/mmyolo#958]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 💬 Describe the reimplementation questions

我想推理一张测试图片，但是找不到相关文件来执行

### Environment

pytorch

**Comment by FunnyWii** [comment]
类似 
python tools/test.py configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_psvoc.py work_dirs/yolov8_s_syncbn_fast_8xb16-500e_psvoc/best_pascal_voc_mAP_epoch_110.pth --show-dir show_results 

见 https://mmyolo.readthedocs.io/zh-cn/latest/get_started/15_minutes_object_detection.html
有推理验证集的方法和deploy模型的方法。

**Comment by todesti2** [comment]
> 类似 python tools/test.py configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_psvoc.py work_dirs/yolov8_s_syncbn_fast_8xb16-500e_psvoc/best_pascal_voc_mAP_epoch_110.pth --show-dir show_results
> 
> 见 https://mmyolo.readthedocs.io/zh-cn/latest/get_started/15_minutes_object_detection.html 有推理验证集的方法和deploy模型的方法。

好嘞！！感谢您帮助我！！我马上去尝试一下

**Comment by todesti2** [comment]
> 类似 python tools/test.py configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_psvoc.py work_dirs/yolov8_s_syncbn_fast_8xb16-500e_psvoc/best_pascal_voc_mAP_epoch_110.pth --show-dir show_results
> 
> 见 https://mmyolo.readthedocs.io/zh-cn/latest/get_started/15_minutes_object_detection.html 有推理验证集的方法和deploy模型的方法。

您好！它这个不能指定单张图片进行推理的吗

**Comment by FunnyWii** [comment]
可以啊，链接内容最下面就是啊
```
python projects/easydeploy/tools/image-demo.py \
    data/cat/images/IMG_20210728_205117.jpg \
    configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
    work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/end2end.onnx \
    --device cpu
```

**Comment by todesti2** [comment]
> --device cpu

噢噢，这个是得转换成onnx模型才能用来推理一张非验证集的图片嘛

**Comment by todesti2** [comment]
> 可以啊，链接内容最下面就是啊
> 
> ```
> python projects/easydeploy/tools/image-demo.py \
>     data/cat/images/IMG_20210728_205117.jpg \
>     configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
>     work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/end2end.onnx \
>     --device cpu
> ```

您好，为什么推理出来是这个样子呀
![image](https://github.com/open-mmlab/mmyolo/assets/97581575/e00d27f6-8aba-4594-80e2-c178a8ab9cad)

**Comment by FunnyWii** [comment]
> > 可以啊，链接内容最下面就是啊
> > ```
> > python projects/easydeploy/tools/image-demo.py \
> >     data/cat/images/IMG_20210728_205117.jpg \
> >     configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
> >     work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/end2end.onnx \
> >     --device cpu
> > ```
> 
> 您好，为什么推理出来是这个样子呀 ![image](https://private-user-images.githubusercontent.com/97581575/296181127-e00d27f6-8aba-4594-80e2-c178a8ab9cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDk3NzUsIm5iZiI6MTcwNTA0OTQ3NSwicGF0aCI6Ii85NzU4MTU3NS8yOTYxODExMjctZTAwZDI3ZjYtOGFiYS00NTk0LTgwZTItYzE3OGE4YWI5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA4NTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ODg4NDZmMTkzMGE3Y2I0ZTI1NmIzYmQ2YjNjMDkxNDA5ODlmYWEyOGEzMjFiZDEzMDUwYmY2NmI3MjcyM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pRzICKQcInljgxlE98rXdNlfotxJUEjADqUSqh9opNU)

看上去框画的并没有问题，只是可视化的时候puttext的时候字号大了些

**Comment by todesti2** [comment]
> puttext

嗯嗯！我应该怎么做呢？恳请您的指点

**Comment by todesti2** [comment]
> puttext

您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
![image](https://github.com/open-mmlab/mmyolo/assets/97581575/91084870-fe9f-4fa7-83c2-6ab791959c94)

**Comment by FunnyWii** [comment]
指点谈不上，我没用Python推理过，我一般转TensorRT然后用C++。
如果你使用的是我提到那个方法，
在`image-demo.py`里有一个函数
```
cv2.putText(
                bgr,
                name, (bbox[0], bbox[1] - 2),
                cv2.FONT_HERSHEY_SIMPLEX,
                2.0, [225, 255, 255],
                thickness=3)
```
你可以搜一下形参代表含义，应该有颜色，字体，字号，粗细等，尝试修改一下

**Comment by FunnyWii** [comment]
> 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢

这不是模糊了，粗细没调，太粗了导致看起来是一大坨

**Comment by todesti2** [comment]
> > 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
> 
> 这不是模糊了，粗细没调，太粗了导致看起来是一大坨

原来如此！谢谢您的指点！！~~我马上去了解❤

**Comment by todesti2** [comment]
> > 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
> 
> 这不是模糊了，粗细没调，太粗了导致看起来是一大坨

您好，我想要去掉展示在图片上的分数，当我执行带上--show时，它显示报错
`(mmyolo) root@autodl-container-95b911bb00-94093f09:~/mmyolo# python projects/easydeploy/tools/image-demo.py /root/autodl-tmp/visdrone/VisDrone2019-DET-test_dev/images/0000006_00159_d_0000001.jpg configs/yolov8/yolov8_l_syncbn_fast_8xb16-500e_coco.py  work_dir/epoch_140.onnx  --device cpu --show
[                                                  ] 0/1, elapsed: 0s, ETA:qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/miniconda3/envs/mmyolo/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)`

并且我发现对应文件夹下是空的 ，尝试了很久还是找不到解决方案
![image](https://github.com/open-mmlab/mmyolo/assets/97581575/0b756341-edd1-42ac-9872-be1c779dd87b)

**Comment by todesti2** [comment]
> > > 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
> > 
> > 
> > 这不是模糊了，粗细没调，太粗了导致看起来是一大坨
> 
> 您好，我想要去掉展示在图片上的分数，当我执行带上--show时，它显示报错 `(mmyolo) root@autodl-container-95b911bb00-94093f09:~/mmyolo# python projects/easydeploy/tools/image-demo.py /root/autodl-tmp/visdrone/VisDrone2019-DET-test_dev/images/0000006_00159_d_0000001.jpg configs/yolov8/yolov8_l_syncbn_fast_8xb16-500e_coco.py work_dir/epoch_140.onnx --device cpu --show [ ] 0/1, elapsed: 0s, ETA:qt.qpa.xcb: could not connect to display qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/miniconda3/envs/mmyolo/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb.
> 
> Aborted (core dumped)`
> 
> 并且我发现对应文件夹下是空的 ，尝试了很久还是找不到解决方案 ![image](https://private-user-images.githubusercontent.com/97581575/296195880-0b756341-edd1-42ac-9872-be1c779dd87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTQyMjAsIm5iZiI6MTcwNTA1MzkyMCwicGF0aCI6Ii85NzU4MTU3NS8yOTYxOTU4ODAtMGI3NTYzNDEtZWRkMS00MmFjLTk4NzItYmUxYzc3OWRkODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEwMDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTUxNGY5NmMzZmVjMWY5YTc5NDQyOTI3Y2FjZmJiMjQ3YTA0MGIxMDMwMWU1MjBjNjU3NzllYWFhZDZiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sgKj4EZpWw6qS91YoFE2axTMt6ktnQiGQXTOavC2ODs)

这个问题我实在解决不了，放弃算了哈哈

**Comment by todesti2** [comment]
> > 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
> 
> 这不是模糊了，粗细没调，太粗了导致看起来是一大坨

我有个非常重要的问题！
1.这个cls数字能否改成类别的名称呀？


![image](https://github.com/open-mmlab/mmyolo/assets/97581575/6f8edb1a-3fac-4aaf-a632-b4c7060f30ea)

**Comment by FunnyWii** [comment]
> > > 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
> > 
> > 
> > 这不是模糊了，粗细没调，太粗了导致看起来是一大坨
> 
> 我有个非常重要的问题！ 1.这个cls数字能否改成类别的名称呀？
> 
> ![image](https://private-user-images.githubusercontent.com/97581575/296202302-6f8edb1a-3fac-4aaf-a632-b4c7060f30ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODE2MzcsIm5iZiI6MTcwNTI4MTMzNywicGF0aCI6Ii85NzU4MTU3NS8yOTYyMDIzMDItNmY4ZWRiMWEtM2ZhYy00YWFmLWE2MzItYjRjNzA2MGYzMGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAxMTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDU4M2I2MzE2YWVkYjA1MjNkZWZmYjI1M2YxMzc0ODQwZGNhMzIyMDE2NjU4Y2ZlZWUxMjI2ZmI0NzMxZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Opo9ia1B7lxHVS9ETAr-7s410NMIW0DzrtAAaX0nbx4)

都是可以的。这个也是puttext画出来的

**Comment by todesti2** [comment]
> > > > 您好！我调小了puttext，但是它变得非常模糊，我该怎么办呢
> > > 
> > > 
> > > 这不是模糊了，粗细没调，太粗了导致看起来是一大坨
> > 
> > 
> > 我有个非常重要的问题！ 1.这个cls数字能否改成类别的名称呀？
> > ![image](https://private-user-images.githubusercontent.com/97581575/296202302-6f8edb1a-3fac-4aaf-a632-b4c7060f30ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODE2MzcsIm5iZiI6MTcwNTI4MTMzNywicGF0aCI6Ii85NzU4MTU3NS8yOTYyMDIzMDItNmY4ZWRiMWEtM2ZhYy00YWFmLWE2MzItYjRjNzA2MGYzMGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAxMTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDU4M2I2MzE2YWVkYjA1MjNkZWZmYjI1M2YxMzc0ODQwZGNhMzIyMDE2NjU4Y2ZlZWUxMjI2ZmI0NzMxZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Opo9ia1B7lxHVS9ETAr-7s410NMIW0DzrtAAaX0nbx4)
> 
> 都是可以的。这个也是puttext画出来的

哈哈，我找到了那个文件，尝试改成类别名但失败了，能请教一下您吗

**Comment by imangoa** [comment]
为什么速度这么慢，比用yolov5慢好多好多
