### ISSUE TITLE
When will the YOLOv9 algorithm go live in the MMYOLO project?

### ISSUE THREAD

**Issue by finestprogrammer** [open-mmlab/mmyolo#973]
### What is the problem this feature will solve?

YOLO has been updated to v9.

### What is the feature you are proposing to solve the problem?

Further improve the accuracy of target detection.

**Comment by WangFengtu1996** [comment]
+1 mark

**Comment by Howe-Young** [comment]
+1 mark

**Comment by Adonis2018** [comment]
+1 mark

**Comment by aeeeeeep** [comment]
+1 mark

**Comment by thiagoribeirodamotta** [comment]
+1 mark

**Comment by JasonYangCode** [comment]
+1 mark

**Comment by clw5180** [comment]
-1 mark
