### ISSUE TITLE
file format partition failure on Windows 10

### ISSUE THREAD

**Issue by SunshinePi** [open-mmlab/mmyolo#99]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

File location: mmengine\config\config.py
Code line: line# 550 
Code: file_format = filename.partition('.')[-1]
Bug: file format after partition is not 'py' but a file name.
Bug reason: the parameter 'filename' is a very long name with 2 dots inside.

### Environment

sys.platform: win32
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: False
numpy_random_seed: 2147483648
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31107 for x64
GCC: n/a
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1
OpenCV: 4.6.0
MMEngine: 0.1.0
MMCV: 2.0.0rc1
MMDetection: 3.0.0rc1
MMYOLO: 0.1.0+5eb6094

**Comment by hhaAndroid** [comment]
@SunshinePi Thank you very much, let's check the window

**Comment by vansin** [comment]
Please provide the command you start the train.py like 

```shell
python tools/train.py configs/xxxx.py
```

**Comment by SunshinePi** [comment]
Sorry that I replied you late,  the issue is not fixed.

**Comment by vansin** [comment]
can you try in latest mmyolo mmengine version?

**Comment by SunshinePi** [comment]
I re-downloaded mmyolo code, and re-installed dependencies.

During the running in my computer, The filename  value is: 'C:\\Users\\FENG~1.ZHA\\AppData\\Local\\Temp\\tmp93ajmopa\\tmp3l2tqy_w.py'


TorchVision: 0.13.1
OpenCV: 4.6.0
MMEngine: 0.3.1
MMCV: 2.0.0rc1
MMDetection: 3.0.0rc3
MMYOLO: 0.1.3+178b0bf
